### ISSUE TITLE
setChildNodesLayout fails, getChildNodesLayout is missing in API for v1.11.1

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1015]
In the scripting API for v1.11.1-pre14
* `node.setChildNodesLayout(...)` fails with an error
* `node.getChildNodesLayout()` is missing

[bug-v11-api-ChildNodesLayout.mm.zip](https://github.com/freeplane/freeplane/files/10776697/bug-v11-api-ChildNodesLayout.mm.zip)

Execution of the following script (`script1`)
```groovy
import org.freeplane.api.ChildNodesLayout

node.setChildNodesLayout(ChildNodesLayout.AUTO_LAST)
```
results in
```
org.freeplane.plugin.script.ExecuteScriptException: org/freeplane/features/layout/LayoutController
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:129)
	at org.freeplane.plugin.script.ScriptRunner.execute(ScriptRunner.java:56)
	at org.freeplane.plugin.script.ScriptingEngine.executeScript(ScriptingEngine.java:58)
	at org.freeplane.plugin.script.ScriptEditor$NodeScriptModel.executeScript(ScriptEditor.java:123)
	at org.freeplane.plugin.script.ScriptEditorPanel$RunAction.actionPerformed(ScriptEditorPanel.java:209)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
	at java.desktop/javax.swing.plaf.basic.BasicPopupMenuUI$BasicMenuKeyListener.menuKeyPressed(BasicPopupMenuUI.java:389)
	at java.desktop/javax.swing.JPopupMenu.fireMenuKeyPressed(JPopupMenu.java:1455)
	at java.desktop/javax.swing.JPopupMenu.processMenuKeyEvent(JPopupMenu.java:1434)
	at java.desktop/javax.swing.JPopupMenu.processKeyEvent(JPopupMenu.java:1418)
	at java.desktop/javax.swing.MenuSelectionManager.processKeyEvent(MenuSelectionManager.java:480)
	at java.desktop/javax.swing.plaf.basic.BasicPopupMenuUI$MenuKeyboardHelper.keyPressed(BasicPopupMenuUI.java:1245)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6584)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2896)
	at java.desktop/java.awt.Component.processEvent(Component.java:6403)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: org/freeplane/features/layout/LayoutController
	at org.freeplane.plugin.script.proxy.NodeProxy.setChildNodesLayout(NodeProxy.java:1106)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at Script1.run(Script1.groovy:3)
	at org.freeplane.plugin.script.GroovyScript.execute(GroovyScript.java:114)
	... 49 more
Caused by: java.lang.ClassNotFoundException: org.freeplane.features.layout.LayoutController
	... 53 more
```

**Comment by dpolivaev** [comment]
Preview 1.11.1_16
