### ISSUE TITLE
trying to run 1.6.15 on ubuntu 18.04 results in `java.awt.AWTError: Assistive Technology not found...`

### ISSUE THREAD

**Issue by sdanieru** [freeplane/freeplane#107]
Howdy!

I'm on Ubuntu 18.04 - I just downloaded the latest stable 'freeplane_bin-1.6.15.zip' and tried to run the executable and I get:

`Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at org.freeplane.launcher.Launcher.fixX11AppName(Launcher.java:51)
	at org.freeplane.launcher.Launcher.main(Launcher.java:65)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 13 more
`

I verified that I have `default-jdk` installed, which is currently wrapping `openjdk-11-jdk`. I installed `openjdk-8-jdk` in the hope it wanted something from there, but still no beans.

**Comment by fnatter** [comment]
hi,
here is the ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1788250
(many applications are affected).

Make sure you use openjdk-8, as openjdk-10 is not working with freeplane at all (and openjdk-11
probably needs changes to freeplane). I am not sure whether #1788250 also applies to openjdk-8-jdk. 
Did you activate the jdk-8 with update-java-alternatives or by setting JAVA_HOME?

Cheers and Best Regards,
Felix

**Comment by dpolivaev** [comment]
For me, it looks rather like you have your openjdk-8-jdk in a headless version without the ui components

**Comment by dpolivaev** [comment]
In any case, the problem is not specific to Freeplane. Try to google for "java.awt.AWTError: Assistive Technology not found" and you find some.

**Comment by sdanieru** [comment]
Thanks gentlemen, appreciate it! I used this workaround: https://sourceforge.net/p/freeplane/bugs/2605/
