### ISSUE TITLE
1.6.13-1 not work oracle java8 Bionic

### ISSUE THREAD

**Issue by EBII** [freeplane/freeplane#110]
Hello 
there is a trouble with version when add oracle java on ubuntu, freeplane didn't show any interface....
fresh ubuntu lts 18.04 with Oracle java8 from webup8team 
this is the output 

tonton@x231:~$ freeplane --version
org.knopflerfish.framework.readonly=true
org.knopflerfish.gosg.jars=reference:file:/usr/share/freeplane/core/
org.freeplane.user.dir=/home/tonton
org.freeplane.basedirectory=/usr/share/freeplane
java.security.policy=/usr/share/freeplane/freeplane.policy
org.osgi.framework.storage=/usr/share/freeplane/fwdir
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/knopflerfish/framework/Main has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.freeplane.launcher.Launcher.run(Launcher.java:127)
	at org.freeplane.launcher.Launcher.launch(Launcher.java:80)
	at org.freeplane.launcher.Launcher.main(Launcher.java:67)

regards

**Comment by fnatter** [comment]
hi EBII,

the problem is that knopflerfish 6.1.1-3 did not make it into bionic.
Please see my reply here:
https://bugs.launchpad.net/ubuntu/+source/freeplane/+bug/1800147

Cheers and Best Regards,
Felix
