### ISSUE TITLE
Icons not in XHTML (JavaScript version)

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1176]
### Discussed in https://github.com/freeplane/freeplane/discussions/1175

<div type='discussions-op-text'>

<sup>Originally posted by **ara1913** May 26, 2023</sup>
Hi,

I use Freeplane to make notes for my studies. I've found that exporting a map as the "XHTML (JavaScript version) is the one I like, as it keeps colors and icons. Recently, I have no icons in my exports. I am a pretty basic user with limited knowledge, but it looks like it has something to do with the directory/path where icons are stored. Exporting a map generates the following error log:

STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:10 AM com.kitfox.svg.xml.StyleSheet parseSheet
WARNING: CSS parser not implemented yet
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\andre\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\andre\AppData\Roaming\Freeplane\1.11.x\lib]
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 26, 2023 10:34:12 AM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 26, 2023 10:34:14 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: May 26, 2023 10:34:17 AM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: May 26, 2023 10:34:34 AM org.freeplane.core.util.LogUtils severe
SEVERE: 
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ".s"
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at org.freeplane.core.util.FileUtils.copyFromURL(FileUtils.java:31)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.copyIconsToDirectory(ExportWithXSLT.java:91)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.copyIcons(ExportWithXSLT.java:130)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.export(ExportWithXSLT.java:243)
	at org.freeplane.features.export.mindmapmode.ExportDialog.export(ExportDialog.java:189)
	at org.freeplane.features.export.mindmapmode.ExportAction.actionPerformed(ExportAction.java:52)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
STDOUT: May 26, 2023 10:34:43 AM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/andre/AppData/Roaming/Freeplane/1.11.x/logs/]

Any help would be greatly appreciated, exams are coming up!
</div>

**Comment by dpolivaev** [comment]
@ara1913  Thanks for reporting it, I am working  on the fix

**Comment by dpolivaev** [comment]
@ara1913 the fix is available in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
Preview 1.11.3_04
