### ISSUE TITLE
BasicHTML$Renderer installed into MainView instead of ScaledHTML$Renderer

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1251]
````
June 21, 2023, 6:43
at 2023-06-21 06:43:47 CMT,  hash c8462c1aba5e32d83532d71b0bfb7f22
previous report : no reports sent before
freeplane_version = 1.11.5; freeplane_xml_version = freeplane 1.11.5
git revision = d873d8985e297dd62262f587afe3f64588bd7244 dpolivaev 2023-06-19T20:27:33Z
java_version = 17.0.7; os_name = Linux; os_version = 6.1.0-9-amd64
Exception in thread "AWT-EventQueue-0" 
java.lang.ClassCastException: class javax.swing.plaf.basic. cannot be cast to class org.freeplane.core.ui.components.html.ScaledHTML$Renderer (javax.swing.plaf.basic.BasicHTML$Renderer is in module java.desktop of loader 'bootstrap'; org.freeplane.core.ui.components.html.ScaledHTML$Renderer is in unnamed module of loader org.knopflerfish.framework.BundleClassLoader @54f9c7bd)

	at org.freeplane.core.ui.components.html.ScaledHTML.updateRendererOnForegroundChange(ScaledHTML.java:70)

	at org.freeplane.view.swing.map.ZoomableLabelUI.propertyChange(ZoomableLabelUI.java:431)

	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)

	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)

	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)

	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8722)

	at java.desktop/java.awt.Component.setForeground(Component.java:1829)

	at java.desktop/javax.swing.JComponent.setForeground(JComponent.java:2771)

	at org.freeplane.view.swing.map.MainView.updateTextColor(MainView.java:504)

	at org.freeplane.view.swing.map.NodeView.update(NodeView.java:1670)

	at org.freeplane.view.swing.map.NodeView.updateAll(NodeView.java:1843)

	at org.freeplane.view.swing.map.MapView.updateAllNodeViews(MapView.java:188)

	at org.freeplane.view.swing.map.MapView.mapChanged(MapView.java:1274)

	at org.freeplane.features.map.MapModel.fireMapChangeEvent(MapModel.java:110)

	at org.freeplane.features.map.MapController.fireMapChanged(MapController.java:649)

	at org.freeplane.features.filter.FilterController.refreshMap(FilterController.java:468)

	at org.freeplane.features.filter.FilterController.applyFilter(FilterController.java:459)

	at org.freeplane.features.presentations.mindmapmode.Slide.applyFilter(Slide.java:477)

	at org.freeplane.features.presentations.mindmapmode.Slide.apply(Slide.java:346)

	at org.freeplane.features.presentations.mindmapmode.PresentationState.showPresentation(PresentationState.java:68)

	at org.freeplane.features.presentations.mindmapmode.PresentationState.changeSlide(PresentationState.java:224)

	at org.freeplane.features.presentations.mindmapmode.PresentationController$7.onCollectionChange(PresentationController.java:165)

	at org.freeplane.features.presentations.mindmapmode.NamedElementCollection.fireCollectionChangeEvent(NamedElementCollection.java:99)

	at org.freeplane.features.presentations.mindmapmode.NamedElementCollection.access$300(NamedElementCollection.java:18)

	at org.freeplane.features.presentations.mindmapmode.NamedElementCollection$1.contentsChanged(NamedElementCollection.java:47)

	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)

	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)

	at org.freeplane.features.presentations.mindmapmode.NamedElementCollection.selectCurrentElement(NamedElementCollection.java:88)

	at org.freeplane.features.presentations.mindmapmode.PresentationState.showNextSlide(PresentationState.java:113)

	at org.freeplane.features.presentations.mindmapmode.NavigationPanelController$ShowNextSlideAction.actionPerformed(NavigationPanelController.java:77)

	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)

	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)

	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)

	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)

	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)

	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)

	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)

	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)

	at java.desktop/java.awt.Component.processEvent(Component.java:6391)

	at java.desktop/java.awt.Container.processEvent(Container.java:2266)

	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)

	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)

	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)

	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)

	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)

	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)

	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)

	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)

	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)

	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)

	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)

	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)

	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)

	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)

	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)

	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)

	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

````

**Comment by dpolivaev** [comment]
@amariusz I do not know how to reproduce it. I need a map and detailed instructions. I do not think it is related to presentation feature.

**Comment by amariusz** [comment]
Please try with this file. Just go to presentation tab and then click "next slide" few times.

[presentation_test_issue.zip](https://github.com/freeplane/freeplane/files/11815295/presentation_test_issue.zip)

I'm not able to reproduce this bug report on my computer but that may be because I've already submitted this report. I was able to reproduce it on other machine (also 1.11.5-pre13 but with windows).

Thanks

**Comment by dpolivaev** [comment]
Many thanks.
I think I understand now where it comes from.

**Comment by dpolivaev** [comment]
If I see it right the bug needs many conditions to be reproduced and I am even not able to reproduce it here. But I found one path where it could happen and I am trying to prevent it.

**Comment by amariusz** [comment]
Right, it's kind of intermittent. I've managed to reproduce it again (or something similar that resulted in freeplane crash) on Linux computer by changing selected node and randomly clicking on next/prev slide, first/prev, start/stop presentation. It takes a dozen or so attempts.

**Comment by amariusz** [comment]
Try following steps. It seems to crash Freeplane every single time.

1. Open the file
2. Click node 1
3. Press space (fold)
4. Go to presentations tab
5. Click play
6. Click next slide 3 times

**Comment by amariusz** [comment]
Another way to trigger bug report - open this file, go to presentations, click play and exit FreePlane.

**Comment by dpolivaev** [comment]
I see, and the steps you describe show another issue.
Unfortunately, I do not have time at the moment.

**Comment by dpolivaev** [comment]
Originally I assumed that all new roots must be either descendants or ancestors of the current root, but using slides to change roots makes this assumption no longer valid. It is the reason for the bug.

**Comment by amariusz** [comment]
I understand. If you attempt to reproduce `BasicHTML$Renderer` error in the future, try this recipe... 
It triggers this error report on windows machine every time, but not on my other linux machine.

1. Open the file
2. Click on root node to select it
3. Go to presentation
4. Click next slide 3 times
5. Click prev slice 3 times
6. Click play
7. Click next slide 3 times.

**Comment by dpolivaev** [comment]
You discover important stuff. Unfortunately I can't work on it longer right now.

**Comment by dpolivaev** [comment]
Preview 1.11.5_14

**Comment by amariusz** [comment]
That was quick! 
I've checked all three scenarios on 1.11.5_14. No crashes or error reports!

One detail that probably still could be improved in this case:
> open this file, go to presentations, click play and exit FreePlane.

Currently you have to press close (X) two times to quit FreePlane.

Thanks!
