### ISSUE TITLE
NoClassDefFoundError: org/freeplane/core/ui/sounds/SoundClipPlayer

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1269]
Further to
- #890 

Steps to reproduce:
1. Open `Tools->Edit script…`
2. Execute the code `logger.severe('test sound')`
3. No sound is played (error log below)

```
Jun 27, 2023 7:29:49 PM org.freeplane.core.util.LogUtils severe
SEVERE: test sound
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/freeplane/core/ui/sounds/SoundClipPlayer
        at org.freeplane.plugin.bugreport.ReportGenerator$2.run(ReportGenerator.java:265)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.freeplane.core.ui.sounds.SoundClipPlayer
        at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:176)
        at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:305)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 14 more
```

**Comment by dpolivaev** [comment]
Preview 1.11.5_15
