### ISSUE TITLE
Error: Heap space not enough when exporting to PDF or JPG

### ISSUE THREAD

**Issue by PromethiumL** [freeplane/freeplane#127]
# What I got
The problem happens when I'd like to export a quite large mm file to PDF.
![image](https://user-images.githubusercontent.com/22100064/52916581-5d5d3080-331c-11e9-9f99-210ea42be8f3.png)
like that. 
According to the statistic info, this mm has about 1200 nodes, among which 600 are leaf nodes.
It works well if I just export some of the branches separately. 

# Error log
```
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuffer.append(StringBuffer.java:270)
	at java.io.StringWriter.write(StringWriter.java:101)
	at org.apache.fop.svg.PDFGraphics2D.processPathIterator(PDFGraphics2D.java:1648)
	at org.apache.fop.svg.PDFGraphics2D.fill(PDFGraphics2D.java:1586)
	at org.apache.batik.gvt.FillShapePainter.paint(FillShapePainter.java:83)
	at org.apache.batik.gvt.CompositeShapePainter.paint(CompositeShapePainter.java:126)
	at org.apache.batik.gvt.ShapeNode.primitivePaint(ShapeNode.java:153)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.ShapeNode.paint(ShapeNode.java:143)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.CanvasGraphicsNode.primitivePaint(CanvasGraphicsNode.java:159)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.fop.svg.PDFTranscoder.transcode(PDFTranscoder.java:185)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at org.freeplane.plugin.svg.ExportPdf.export(ExportPdf.java:87)
	at org.freeplane.features.export.mindmapmode.ExportDialog.export(ExportDialog.java:184)
	at org.freeplane.features.export.mindmapmode.ExportAction.actionPerformed(ExportAction.java:52)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:92)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
```
if I choose JPG.
A dialog will immediately popup saying memory overflow.

# Environment
Linux 4.15.0-43-generic #46-Ubuntu 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

Could that be solved by adding some arguments to then program? 
Hope this issue can be fixed. Thanks! :)

**Comment by inglor** [comment]
Have you try adjusting the freeplane.sh Xmx jvm argument like below:
```
$ diff freeplane.sh-old freeplane.sh-new
194c194
< "${JAVACMD}" -Xmx512m\
---
> "${JAVACMD}" -Xmx2G\
```
