### ISSUE TITLE
FP 1,11,4

### ISSUE THREAD

**Issue by Eremos** [freeplane/freeplane#1284]
I don't understand this errors (logs)
what can I do to avoid these errors?

*********** log begin ------------------
STDOUT: juin 30, 2023 8:03:07 P.M. org.freeplane.core.util.LogUtils info
INFOS: freeplane_version = 1.11.4; freeplane_xml_version = freeplane 1.11.1
git revision = 62e12866e72e5e50519962fccfc06244c3cf4b59 dpolivaev 2023-05-28T13:36:02Z
java_version = 15.0.10; os_name = Windows 11; os_version = 10.0
STDOUT: juin 30, 2023 8:03:07 P.M. org.freeplane.core.util.LogUtils info
INFOS: added parsing support for standard date format y-MM-dd
STDOUT: juin 30, 2023 8:03:07 P.M. org.freeplane.core.util.LogUtils info
INFOS: added parsing support for standard date time format y-MM-dd HH 'h' mm
STDOUT: Framework launched
STDOUT: juin 30, 2023 8:03:09 P.M. org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: juin 30, 2023 8:03:09 P.M. org.freeplane.core.util.LogUtils info
INFOS: extending script's classpath by [C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\lib]
STDOUT: juin 30, 2023 8:03:09 P.M. org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDERR: juin 30, 2023 8:03:10 P.M. org.freeplane.core.util.LogUtils severe
GRAVE: error compiling in C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\lib[GtdReportController.groovy, GtdReportViewController.groovy, GTDMapChangeListener.groovy, GTDMapSelectionListener.groovy, GTDNodeChangeListener.groovy, ClipBoardUtil.groovy, DateUtil.groovy, IconUtil.groovy, Tag.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\lib\freeplaneGTD\GtdReportViewController.groovy: 9: unable to resolve class org.freeplane.core.ui.components.MultipleImage
 @ line 9, column 1.
   import org.freeplane.core.ui.components.MultipleImage
   ^

C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\lib\freeplaneGTD\listener\GTDNodeChangeListener.groovy: 3: unable to resolve class freeplaneGTD.GTDMapReader
 @ line 3, column 1.
   import freeplaneGTD.GTDMapReader
   ^

C:\Users\lucjo\AppData\Roaming\Freeplane\1.11.x\lib\freeplaneGTD\util\ClipBoardUtil.groovy: 3: unable to resolve class freeplaneGTD.GTDMapReader
 @ line 3, column 1.
   import freeplaneGTD.GTDMapReader
   ^

3 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:909)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:647)
	at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:316)
	at org.freeplane.plugin.script.ClasspathScriptCompiler.compile(ClasspathScriptCompiler.java:131)
	at org.freeplane.plugin.script.ClasspathScriptCompiler.compile(ClasspathScriptCompiler.java:110)
	at org.freeplane.plugin.script.ClasspathScriptCompiler.compileScriptsInDirectory(ClasspathScriptCompiler.java:94)
	at org.freeplane.plugin.script.ClasspathScriptCompiler.compileLibraryScripts(ClasspathScriptCompiler.java:75)
	at org.freeplane.plugin.script.ClasspathScriptCompiler.compileScriptsOnPath(ClasspathScriptCompiler.java:62)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:185)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:27)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:256)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:272)
	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:62)
	at org.freeplane.main.osgi.ActivatorImpl$1.run(ActivatorImpl.java:196)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
STDOUT: juin 30, 2023 8:03:10 P.M. org.freeplane.core.util.LogUtils info
INFOS: looking for scripts with the following endings: [groovy]
STDOUT: juin 30, 2023 8:03:10 P.M. org.freeplane.core.util.LogUtils info
INFOS: looking for scripts with the following endings: [groovy]
STDOUT: juin 30, 2023 8:03:12 P.M. org.freeplane.core.util.LogUtils info
INFOS: requesting mode: MindMap
STDOUT: juin 30, 2023 8:03:14 P.M. org.freeplane.core.util.LogUtils info
INFOS: menu items to execute: []
STDOUT: juin 30, 2023 8:05:09 P.M. org.freeplane.core.util.LogUtils info
INFOS: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/lucjo/AppData/Roaming/Freeplane/1.11.x/logs/]

**Comment by dpolivaev** [comment]
Your installed version of GTD add-on tries to use the internal Freeplane class `org.freeplane.core.ui.components.MultipleImage` which has been deleted or changed in a non-compatible way. 

You can uninstall or update it if a version working with the latest freeplane version is already available. If you need the old version of GTD add-on you can downgrade Freeplane.
