### ISSUE TITLE
Java heap space exception when loading many HTML images

### ISSUE THREAD

**Issue by guoranjun2** [freeplane/freeplane#1322]
**Describe the bug**
I have a large number of HTML images in details, If I display them at the same time, the above-mentioned error will occur.
I tried to allocate 4GB of memory to Freeplane, but it didn't work. This error occurred when the Windows Task Manager showed its memory usage was 1.3GB.

log info:
```
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
STDERR: at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:539)
STDERR: at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
STDERR: at java.desktop/sun.awt.image.ImageRepresentation.createBufferedImage(ImageRepresentation.java:253)
STDERR: at java.desktop/sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:559)
STDERR: at java.desktop/sun.awt.image.ImageDecoder.setPixels(ImageDecoder.java:138)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.sendPixels(JPEGImageDecoder.java:120)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.readImage(Native Method)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:142)
STDERR: at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:270)
STDERR: at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
STDERR: at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NoClassDefFoundError: org/freeplane/core/ui/sounds/SoundClipPlayer
STDERR: at org.freeplane.plugin.bugreport.ReportGenerator$2.run(ReportGenerator.java:265)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Caused by: java.lang.ClassNotFoundException: org.freeplane.core.ui.sounds.SoundClipPlayer
STDERR: at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:176)
STDERR: at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:305)
STDERR: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
STDERR: ... 14 more
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
STDERR: at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:539)
STDERR: at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
STDERR: at java.desktop/sun.awt.image.ImageRepresentation.createBufferedImage(ImageRepresentation.java:253)
STDERR: at java.desktop/sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:559)
STDERR: at java.desktop/sun.awt.image.ImageDecoder.setPixels(ImageDecoder.java:138)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.sendPixels(JPEGImageDecoder.java:120)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.readImage(Native Method)
STDERR: at java.desktop/sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:142)
STDERR: at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:270)
STDERR: at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
STDERR: at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
STDERR: Exception in thread "Image Fetcher 0"
STDERR: java.lang.OutOfMemoryError: Java heap space
```

**To Reproduce**
open mind map, unfold all nodes. see attachment.

**Mind map files**
[Java heap space when loading many HTML images.zip](https://github.com/freeplane/freeplane/files/12223641/Java.heap.space.when.loading.many.HTML.images.zip)

**Screenshots**
the mind map:
![image](https://github.com/freeplane/freeplane/assets/50692082/5cc3e202-f7ef-43c8-bc0e-928c56909450)

memory usage：
![image](https://github.com/freeplane/freeplane/assets/50692082/ab21d8af-5b99-4ec5-ae56-122292cddcfd)

**Desktop (please complete the following information):**
 - OS: win11
 - Version freeplane: 1.11.5
 - Java Version: java17

**Comment by dpolivaev** [comment]
Sorry, I can not help.
