### ISSUE TITLE
Failure to Launch after Update to 1.11.5 from 1.11.4

### ISSUE THREAD

**Issue by yellek** [freeplane/freeplane#1343]
### Discussed in https://github.com/freeplane/freeplane/discussions/1342

<div type='discussions-op-text'>

<sup>Originally posted by **yellek** August 16, 2023</sup>
I updated to the latest version and Freeplane.exe now does not launch. Freeplane.exe exits without a message. Freeplane.bat is throwing an error.

C:\Program Files\Freeplane>java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

C:\Program Files\Freeplane>java --add-exports=java.desktop/sun.awt.shell=ALL-UNNAMED --add-exports=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED -Xmx512m -Dorg.freeplane.userfpdir="C:\Users\<user>\AppData\Roaming\\Freeplane" -jar freeplanelauncher.jar
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:429)
        at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:291)
        at org.freeplane.launcher.Launcher.main(Launcher.java:88)</div>

**Comment by dpolivaev** [comment]
Yes, using the setup with Java is the easiest solution you can use.
