### ISSUE TITLE
Hidding a "jumped in" or hiding using filter "root" node throws error

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#1358]
**Describe the bug**
when selecting a node and "jumping in". If you define that node as hidden node FP throws an error.

**To Reproduce**
1. menu option "Show hidden nodes"  (`View->Show hidden nodes`) is unchecked
2. Select a node
![image](https://github.com/freeplane/freeplane/assets/35700575/22b5a6de-7ef9-4162-bdfb-6169ca61ce18)

3. Jump in
![image](https://github.com/freeplane/freeplane/assets/35700575/91bc15ac-a6a7-463d-a113-f3118e989054)

4. Click on menu commad `View->Hidden node`
5. See error

**Expected behavior**
Any of these:
- node should disappear 
- operation should be forbiden and it should display a message to the user  

**Desktop (please complete the following information):**
 - OS: win10
 - Version FP v1.11.6_4
 - Java Version

**Additional context**
Log:

<details> <summary> Log0 text </summary>

```log




STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "org.freeplane.view.swing.map.NodeView.isFolded()" because "parentView" is null
STDERR: at org.freeplane.view.swing.map.NodeView.nodeChanged(NodeView.java:1097)
STDERR: at org.freeplane.features.map.NodeModel.lambda$fireNodeChanged$2(NodeModel.java:241)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:238)
STDERR: at org.freeplane.features.map.NodeModel.fireSingleNodeChanged(NodeModel.java:231)
STDERR: at org.freeplane.features.map.NodeModel.lambda$fireNodeChanged$1(NodeModel.java:221)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:218)
STDERR: at org.freeplane.features.map.MapController.fireNodeChanged(MapController.java:684)
STDERR: at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:963)
STDERR: at org.freeplane.features.map.MapController.nodeChanged(MapController.java:907)
STDERR: at org.freeplane.features.map.mindmapmode.MMapController$12.act(MMapController.java:1235)
STDERR: at org.freeplane.features.mode.mindmapmode.MModeController.lambda$execute$0(MModeController.java:187)
STDERR: at org.freeplane.features.ui.FrameController$StaticInvoker.invokeAndWait(FrameController.java:936)
STDERR: at org.freeplane.features.ui.FrameController$StaticInvoker.access$500(FrameController.java:933)
STDERR: at org.freeplane.features.ui.FrameController.invokeAndWait(FrameController.java:930)
STDERR: at org.freeplane.features.mode.mindmapmode.MModeController.execute(MModeController.java:185)
STDERR: at org.freeplane.features.map.mindmapmode.MMapController.setProperty(MMapController.java:1238)
STDERR: at org.freeplane.features.map.mindmapmode.MMapController.setProperty(MMapController.java:1209)
STDERR: at org.freeplane.core.enumeration.NodeEnumerationAction.actionPerformed(NodeEnumerationAction.java:37)
STDERR: at org.freeplane.core.ui.AMultipleNodeAction.actionPerformed(AMultipleNodeAction.java:49)
STDERR: at org.freeplane.core.enumeration.NodeEnumerationAction.actionPerformed(NodeEnumerationAction.java:28)
STDERR: at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
STDERR: at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
STDERR: at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
STDERR: at org.freeplane.core.ui.components.ActionToggleButtonModel.fireActionPerformed(ActionToggleButtonModel.java:54)
STDERR: at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
STDERR: at org.freeplane.core.ui.components.ActionToggleButtonModel.setPressed(ActionToggleButtonModel.java:34)
STDERR: at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
STDERR: at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
STDERR: at java.desktop/java.awt.Component.processEvent(Unknown Source)
STDERR: at java.desktop/java.awt.Container.processEvent(Unknown Source)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
STDERR: at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
STDERR: at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)


```
</details>

**Comment by dpolivaev** [comment]
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
Preview 1.11.7_pre01
Actually, a major issue, the fix is also related to filters and to presentations. 
I hope you have enough use cases to check if it works well now.
