### ISSUE TITLE
error on deleting nodes

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1381]
- created new map
- added two node (abc, def)
- deleted first node (del key)

I deleted the log file before generating the new map. Similar behavior is observed in "old" maps
Identical behavior on two different computers (send error report from the other one)

Edit: Tried portable installs 1.11.6 and 1.11.7 (no scripts, addons etc), portable recommended JRE.  
=> .6 runs as expected; .7 recreates the error above (reported via internal method)
Other menu activities (e.g. exporting branch to new map) generate the error as well</div>

**Comment by EdoFro** [comment]
same error when doing drag&drop

<details> <summary> Log detail </summary>
<code>
STDERR: Sep 05, 2023 8:43:36 PM org.freeplane.core.util.LogUtils severe
SEVERE: Drop exception:
java.lang.NullPointerException: Cannot invoke "org.freeplane.view.swing.map.NodeView.isContentVisible()" because "preferred" is null
	at org.freeplane.view.swing.map.MapView.selectVisibleAncestorOrSelf(MapView.java:2493)
	at org.freeplane.view.swing.map.NodeView.onNodeDeleted(NodeView.java:1222)
	at org.freeplane.features.map.NodeModel.fireNodeRemoved(NodeModel.java:276)
	at org.freeplane.features.map.NodeModel.lambda$fireNodeMoved$3(NodeModel.java:250)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.freeplane.features.map.NodeModel.fireNodeMoved(NodeModel.java:248)
	at org.freeplane.features.map.MapController.fireNodeMoved(MapController.java:713)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodeToWithoutUndo(MMapController.java:866)
	at org.freeplane.features.map.mindmapmode.MMapController.access$100(MMapController.java:118)
	at org.freeplane.features.map.mindmapmode.MMapController$7.act(MMapController.java:716)
	at org.freeplane.features.mode.mindmapmode.MModeController.lambda$execute$0(MModeController.java:187)
	at org.freeplane.features.ui.FrameController$StaticInvoker.invokeAndWait(FrameController.java:936)
	at org.freeplane.features.ui.FrameController$StaticInvoker.access$500(FrameController.java:933)
	at org.freeplane.features.ui.FrameController.invokeAndWait(FrameController.java:930)
	at org.freeplane.features.mode.mindmapmode.MModeController.execute(MModeController.java:185)
	at org.freeplane.features.map.mindmapmode.MMapController.moveSingleNode(MMapController.java:729)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodeAndItsClones(MMapController.java:677)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodes(MMapController.java:600)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodesAsChildren(MMapController.java:743)
	at org.freeplane.view.swing.ui.mindmapmode.MNodeDropListener.moveNodes(MNodeDropListener.java:320)
	at org.freeplane.view.swing.ui.mindmapmode.MNodeDropListener.drop(MNodeDropListener.java:272)
	at java.desktop/java.awt.dnd.DropTarget.drop(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.freeplane.features.map.IMapSelection.getSelected()" is null
STDERR: at org.freeplane.features.styles.mindmapmode.SelectedNodeChangeListener$2.nodeChanged(SelectedNodeChangeListener.java:50)
STDERR: at org.freeplane.features.map.NodeModel.fireSingleNodeChanged(NodeModel.java:229)
STDERR: at org.freeplane.features.map.NodeModel.lambda$fireNodeChanged$1(NodeModel.java:221)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at org.freeplane.features.map.NodeModel.fireNodeChanged(NodeModel.java:218)
STDERR: at org.freeplane.features.map.MapController.fireNodeChanged(MapController.java:684)
STDERR: at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:963)
STDERR: at org.freeplane.features.map.MapController.nodeRefresh(MapController.java:918)
STDERR: at org.freeplane.features.map.MapController$Refresher$1.run(MapController.java:1037)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

</code>
</details>

**Comment by dpolivaev** [comment]
Preview 1.11.7_02
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
