### ISSUE TITLE
null pointer exception occurs when using multi-threading to create nodes 

### ISSUE THREAD

**Issue by guoranjun2** [freeplane/freeplane#1392]
**To Reproduce**
run example script

```groovy
new Thread({
def cur = node
 (1..100).each { 
 	cur = cur.createChild it.toString() 
 	cur.note = "hello world"
 	if(it % 10 == 0) cur = node 
 }
}).start()
```

**Screenshots**
![NPE](https://github.com/freeplane/freeplane/assets/50692082/aa54ea05-720d-4d22-8a34-b5239f3034c9)

**Desktop (please complete the following information):**
 - OS: win11
 - Freeplane Version 1.11.6
 - Java Version java17

**log**
```
STDERR: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "collection" is null
STDERR: at org.freeplane.features.note.NoteController.getNoteContentType(NoteController.java:98)
STDERR: at org.freeplane.plugin.script.proxy.NodeProxy.setNoteText(NodeProxy.java:692)
STDERR: at org.freeplane.plugin.script.proxy.NodeProxy.setNote(NodeProxy.java:684)
STDERR: at jdk.internal.reflect.GeneratedMethodAccessor188.invoke(Unknown Source)
STDERR: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
STDERR: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
STDERR: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
STDERR: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
STDERR: at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2892)
STDERR: at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3890)
STDERR: at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:194)
STDERR: at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:502)
STDERR: at Script1$_run_closure1$_closure2.doCall(Script1.groovy:5)
STDERR: at jdk.internal.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
STDERR: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
STDERR: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
STDERR: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
STDERR: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
STDERR: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
STDERR: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1006)
STDERR: at groovy.lang.Closure.call(Closure.java:433)
STDERR: at groovy.lang.Closure.call(Closure.java:422)
STDERR: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2387)
STDERR: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2372)
STDERR: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2413)
STDERR: at org.codehaus.groovy.runtime.dgm$204.doMethodInvoke(Unknown Source)
STDERR: at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
STDERR: at Script1$_run_closure1.doCall(Script1.groovy:3)
STDERR: at Script1$_run_closure1.doCall(Script1.groovy)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
STDERR: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
STDERR: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
STDERR: at java.base/java.lang.reflect.Method.invoke(Method.java:568)
STDERR: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
STDERR: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
STDERR: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
STDERR: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1006)
STDERR: at groovy.lang.Closure.call(Closure.java:433)
STDERR: at groovy.lang.Closure.call(Closure.java:412)
STDERR: at groovy.lang.Closure.run(Closure.java:505)
STDERR: at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dpolivaev** [comment]
Yes, multithreaing is not supported, you can run all operations on mind maps and UI only in the Swing  Event thread
