### ISSUE TITLE
Not able to move sides with Jump In

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1451]
I'm getting a bug. For now, what I could notice:
- I have multiple map views of the  same map. Some of them with Jump In
- in one of the map views, with Jump In, I have nodes distributed to both sides. (maybe, this is relevant:) I think this distribution happened because this parent node, originally, was on the left side of the Real Root, created some nodes, and then I moved it to the right side of the Real Root, and created a couple more nodes.
- if I try to move a node from one side to the other, I get the error and nothing happens.

Log for this error:
```
STDERR: Oct 07, 2023 10:12:04 AM org.freeplane.core.util.LogUtils severe
SEVERE: Drop exception:
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.desktop/java.awt.Container.remove(Unknown Source)
	at org.freeplane.view.swing.map.MapView.restoreRootNode(MapView.java:2817)
	at org.freeplane.view.swing.map.MapView.restoreRootNode(MapView.java:2802)
	at org.freeplane.view.swing.map.NodeView.onNodeDeleted(NodeView.java:1222)
	at org.freeplane.features.map.NodeModel.fireNodeRemoved(NodeModel.java:276)
	at org.freeplane.features.map.NodeModel.lambda$fireNodeMoved$3(NodeModel.java:250)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.freeplane.features.map.NodeModel.fireNodeMoved(NodeModel.java:248)
	at org.freeplane.features.map.MapController.fireNodeMoved(MapController.java:713)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodeToWithoutUndo(MMapController.java:834)
	at org.freeplane.features.map.mindmapmode.MMapController.access$100(MMapController.java:114)
	at org.freeplane.features.map.mindmapmode.MMapController$7.act(MMapController.java:684)
	at org.freeplane.features.mode.mindmapmode.MModeController.lambda$execute$0(MModeController.java:187)
	at org.freeplane.features.ui.FrameController$StaticInvoker.invokeAndWait(FrameController.java:935)
	at org.freeplane.features.ui.FrameController$StaticInvoker.access$500(FrameController.java:932)
	at org.freeplane.features.ui.FrameController.invokeAndWait(FrameController.java:929)
	at org.freeplane.features.mode.mindmapmode.MModeController.execute(MModeController.java:185)
	at org.freeplane.features.map.mindmapmode.MMapController.moveSingleNode(MMapController.java:697)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodeAndItsClones(MMapController.java:645)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodes(MMapController.java:568)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodesAsChildren(MMapController.java:711)
	at org.freeplane.view.swing.ui.mindmapmode.MNodeDropListener.moveNodes(MNodeDropListener.java:319)
	at org.freeplane.view.swing.ui.mindmapmode.MNodeDropListener.drop(MNodeDropListener.java:271)
	at java.desktop/java.awt.dnd.DropTarget.drop(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

I will try to reproduce.

freeplane_bin-1.11.8-pre02

**Comment by euu2021** [comment]
I restarted FP, and tried a very similar situation, but the bug didn't happen. This will be difficult to reproduce 🐛

**Comment by euu2021** [comment]
I will reopen the issue, if I manage to reproduce.
