### ISSUE TITLE
Mindmap export error when using certain icons

### ISSUE THREAD

**Issue by RalphRWL** [freeplane/freeplane#1485]
**Describe the bug**
When trying to export a mindmap as XHTML (Javascript version) and the mindmap is using the 50%.svg icon, the export fails with the following error: 

at 2023-10-21 21:11:36 CMT,  hash 58035316fe1266542ac41e182a671549
previous report : no reports sent before
freeplane_version = 1.10.6; freeplane_xml_version = freeplane 1.9.13
git revision = 3e6a1230ca958fab95cb83264fd638479f278426 Dimitry Polivaev 2022-12-07T13:14:37Z
java_version = 15.0.7; os_name = Windows 10; os_version = 10.0
Okt. 21, 2023 11:11:35 PM org.freeplane.core.util.LogUtils severe
SCHWERWIEGEND: 
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ".s"
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at java.base/java.net.URLDecoder.decode(Unknown Source)
	at org.freeplane.core.util.FileUtils.copyFromURL(FileUtils.java:31)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.copyIconsToDirectory(ExportWithXSLT.java:91)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.copyIcons(ExportWithXSLT.java:130)
	at org.freeplane.features.export.mindmapmode.ExportWithXSLT.export(ExportWithXSLT.java:243)
	at org.freeplane.features.export.mindmapmode.ExportDialog.export(ExportDialog.java:189)
	at org.freeplane.features.export.mindmapmode.ExportAction.actionPerformed(ExportAction.java:52)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:93)
        ...

Issue also appears for any other of the xxx%.svg icons.

Looks like the this is caused by the % character in the icon's file name. When trying to use the same icon in <freeplane_userdir>/icons with a different name (without %) the export works fine.

**To Reproduce**
1. Create a new mindmap
2. Add a node to the mindmap (any text)
3. Add the 50% icon to the node
4. Try to export the mindmap via mindmap export -> XHTML (JavaScript Version) => Error

**Expected behavior**
Mindmap export completes successfully.

**Mind map files**
[Test.zip](https://github.com/freeplane/freeplane/files/13061860/Test.zip)

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version [e.g. 22]: Freeplane 1.10.6
 - Java Version: 15.0.7

**Additional context**
-

**Comment by dpolivaev** [comment]
Could you please check if the bug is still present in the latest stable version 1.11.6?

**Comment by RalphRWL** [comment]
Thanks for the hint! With 1.11.7 the export works perfectly.
