### ISSUE TITLE
Javafx issues

### ISSUE THREAD

**Issue by HumanG33k** [freeplane/freeplane#152]
On debian testing freeplane/testing,testing,now 1.7.10-1 start in command line show several error.
The jfx is out the jre/jdk since 9 and it become really tricky to have a working configuration(i only have done few tests)

```bash 
❰\_ freeplane 
*org.knopflerfish.framework.readonly=true
*org.knopflerfish.gosg.jars=reference:file:/usr/share/freeplane/core/
*org.freeplane.user.dir=/home/user
*org.freeplane.basedirectory=/usr/share/freeplane
org.freeplane.globalresourcedir=/usr/share/freeplane/resources
*java.security.policy=/usr/share/freeplane/freeplane.policy
*org.osgi.framework.storage=/usr/share/freeplane/fwdir
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2018 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.5.
Background mode.
févr. 25, 2020 3:08:51 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://1:1/freeplane.properties
févr. 25, 2020 3:08:51 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://1:2/org/freeplane/main/application/
févr. 25, 2020 3:08:52 PM org.freeplane.core.util.LogUtils info
INFOS: Listening for application instances on socket 39081
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.formula (id#3)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#4)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.latex (id#5)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.openmaps (id#6)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.script (id#7)
Installed: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.svg (id#8)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.formula (id#3)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#4)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.latex (id#5)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.openmaps (id#6)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.script (id#7)
Started: reference:file:/usr/share/freeplane/plugins/org.freeplane.plugin.svg (id#8)
févr. 25, 2020 3:08:55 PM org.freeplane.core.util.LogUtils info
INFOS: language resources for fr found
févr. 25, 2020 3:08:58 PM org.freeplane.core.util.LogUtils info
INFOS: freeplane_version = 1.7.10; freeplane_xml_version = freeplane 1.7.0
git revision = 34e2242e73d5cf0190a189ef0a60e95b983a3bf1 Dimitry Polivaev 2019-10-25T18:36:32Z
java_version = 11.0.6; os_name = Linux; os_version = 5.4.0-3-amd64
févr. 25, 2020 3:09:45 PM org.freeplane.core.util.LogUtils info
INFOS: added parsing support for standard date format dd/MM/y
févr. 25, 2020 3:09:45 PM org.freeplane.core.util.LogUtils info
INFOS: available locales not found
févr. 25, 2020 3:09:45 PM org.freeplane.core.util.LogUtils info
INFOS: available locales not found
févr. 25, 2020 3:09:47 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
févr. 25, 2020 3:09:48 PM org.freeplane.core.util.LogUtils info
INFOS: extending script's classpath by [/home/user/.config/freeplane/1.7.x/compiledscripts, /home/user/.config/freeplane/1.7.x/lib]
févr. 25, 2020 3:09:48 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://7:1/org/freeplane/plugin/script/defaults.properties
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (bundle://7) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
févr. 25, 2020 3:09:49 PM org.freeplane.core.util.LogUtils severe
GRAVE: error compiling in /home/user/.config/freeplane/1.7.x/lib[Tag.groovy, JSHandler.groovy, ReportWindow.groovy, DoneMover.groovy, ReviewTask.groovy, ArchiveTask.groovy, ReportModel.groovy, ClipBoardUtil.groovy, DateUtil.groovy, GTDMapReader.groovy, MultinodeActionEditor.groovy, ActionEditor.groovy]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home//.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 8: unable to resolve class javafx.embed.swing.JFXPanel
 @ line 8, column 1.
   import javafx.embed.swing.JFXPanel
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 4: unable to resolve class javafx.application.Platform
 @ line 4, column 1.
   import javafx.application.Platform
   ^
/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 6: unable to resolve class javafx.beans.value.ObservableValue
 @ line 6, column 1.
   import javafx.beans.value.ObservableValue
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 7: unable to resolve class javafx.concurrent.Worker
 @ line 7, column 1.
   import javafx.concurrent.Worker
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 5: unable to resolve class javafx.beans.value.ChangeListener
 @ line 5, column 1.
   import javafx.beans.value.ChangeListener
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 11: unable to resolve class javafx.scene.web.WebView
 @ line 11, column 1.
   import javafx.scene.web.WebView
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 9: unable to resolve class javafx.scene.Scene
 @ line 9, column 1.
   import javafx.scene.Scene
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 10: unable to resolve class javafx.scene.web.WebEngine
 @ line 10, column 1.
   import javafx.scene.web.WebEngine
   ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 181: unable to resolve class Worker.State 
 @ line 181, column 78.
   ddListener(new ChangeListener<Worker.Sta
                                 ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 38.
                                                                void changed(ObservableValue<? extends Worker.State> observable, Worker.State oldValue, Worker.State newValue) {
                                        ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 74.
   nds Worker.State> observable, Worker.Sta
                                 ^

/home/user/.config/freeplane/1.7.x/lib/freeplaneGTD/ReportWindow.groovy: 183: unable to resolve class Worker.State 
 @ line 183, column 97.
   vable, Worker.State oldValue, Worker.Sta
                                 ^

12 errors
        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:981)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:575)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:76)
        at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:111)
        at org.freeplane.plugin.script.ScriptCompiler.compile(ScriptCompiler.java:90)
        at org.freeplane.plugin.script.ScriptCompiler.compileScriptsInDirectory(ScriptCompiler.java:74)
        at org.freeplane.plugin.script.ScriptCompiler.compileScriptsOnPath(ScriptCompiler.java:59)
        at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:175)
        at org.freeplane.plugin.script.ScriptingRegistration.<init>(ScriptingRegistration.java:142)
        at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:26)
        at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:280)
        at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:296)
        at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:215)
        at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:109)
        at org.freeplane.main.osgi.Activator.start(Activator.java:35)
        at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:386)
        at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

févr. 25, 2020 3:09:49 PM org.freeplane.core.util.LogUtils info
INFOS: Loaded properties from bundle://7:1/org/freeplane/plugin/script/defaults.properties
févr. 25, 2020 3:09:49 PM org.freeplane.core.util.LogUtils info
INFOS: looking for scripts with the following endings: [groovy, js]
Framework launched
févr. 25, 2020 3:09:50 PM org.freeplane.core.util.LogUtils info
INFOS: requesting mode: MindMap

```

**Comment by fnatter** [comment]
hello,

I guess the names of the openjfx jars changed:
https://packages.debian.org/sid/all/libopenjfx-java/filelist

@vboerchers: Can you tell us how to change the GTD addon to pick up the new jars?

Cheers and Best Regards,
Felix

**Comment by vboerchers** [comment]
Hi @HumanG33k,

I assume that you use the old Freeplane|GTD add-on. This seems to be abandoned, since the link on [Freeplane Add-ons#GTD](https://freeplane.sourceforge.io/wiki/index.php/Add-ons_(install)#Freeplane.7CGTD) is broken.

There's a new add-on, GTD+, to be found at [Freeplane Add-ons#GTD+](https://freeplane.sourceforge.io/wiki/index.php/Add-ons_(install)#Freeplane.7CGTD.2B). Please check that out and add a bug at the add-on's GitHub page if it does not work either.

In any way please post the state of the issue here, since we may have to remove the section to the old add-on from the install page.

Volker

CC: @fnatter

**Comment by HumanG33k** [comment]
Ok thx i will write an email to the debian team in order to manage it.

**Comment by fnatter** [comment]
hi @HumanG33k , please look at what @vboerchers posted, this is likely to be the root cause.
I double-checked and to me, it looks like the openjfx jars did not change since buster.

Cheers and Best Regards,
Felix

**Comment by HumanG33k** [comment]
I just recheck but i just can’t remember if/when i install it. 
btw i just close the issue.
