### ISSUE TITLE
Failing test at 1.8.x branch after commit 752b1d03df4e8bc63e4038a9fdb2246998e95000

### ISSUE THREAD

**Issue by inglor** [freeplane/freeplane#156]
Hi @dpolivaev ,

The following test is failing on 1.8.x branch.
```
> Task :freeplane:test

org.freeplane.core.ui.menubuilders.menu.JMenuItemBuilderTest > whenPopupMenuBecomesInvisible_popupListenerIsCalled FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at JMenuItemBuilderTest.java:257

281 tests completed, 1 failed
```
My gradle version and JDK are
```
$ gradle --version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 22:12:49 UTC
Revision:     <unknown>

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (Oracle Corporation 11.0.6+10)
OS:           Linux 5.6.2-1-gc amd64
```
The failure seems to be introduced with commit `752b1d03df4e8bc63e4038a9fdb2246998e95000`

To reproduce checkout 1.8.x branch and clean build it from command line.

See below for stacktrace.

```
Apr 06, 2020 10:16:32 AM org.freeplane.core.util.LogUtils severe
SEVERE: 
java.lang.RuntimeException: java.lang.NullPointerException
	at org.freeplane.main.headlessmode.FreeplaneHeadlessStarter.createController(FreeplaneHeadlessStarter.java:94)
	at org.freeplane.core.ui.menubuilders.HeadlessFreeplaneRunner.<clinit>(HeadlessFreeplaneRunner.java:15)
	at org.freeplane.core.ui.menubuilders.menu.JMenuItemBuilderTest.<clinit>(JMenuItemBuilderTest.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NullPointerException
	at org.freeplane.core.resources.ResourceBundles.<init>(ResourceBundles.java:64)
	at org.freeplane.core.resources.ResourceController.getResources(ResourceController.java:264)
	at org.freeplane.core.util.TextUtils.getLanguageResources(TextUtils.java:122)
	at org.freeplane.core.util.TextUtils.getRawText(TextUtils.java:98)
	at org.freeplane.core.ui.AFreeplaneAction.<init>(AFreeplaneAction.java:53)
	at org.freeplane.features.mode.MoveToRootAction.<init>(MoveToRootAction.java:37)
	at org.freeplane.features.mode.Controller.<init>(Controller.java:81)
	at org.freeplane.main.headlessmode.FreeplaneHeadlessStarter.createController(FreeplaneHeadlessStarter.java:64)
	... 27 more
```

**Comment by dpolivaev** [comment]
I fixed one test but at some other place.
Now all tests pass on my machine, please check hot it works on yours.

**Comment by inglor** [comment]
Fixed now - thanks.
