### ISSUE TITLE
Editing attributes in "Viewing" mode throws error

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#1578]
**Describe the bug**
When in "Viewing mode", editing an attribute in the toolpanel throws an error and Freeplane becomes "buggy"

**To Reproduce**
1. open a mind map (new or previous one)
2. Click on Menu -> Edit -> View mode
3. Go to the "Attributes" tab in the toolpanel
4. Click on add a new attribute
5. Edit the name of the attribute + tabkey
7. See error

**Expected behavior**
no error.
options:
1. user can't add a new attribute or edit them in the panel
2. user can do both, but this doesn't change the node

<details><summary> <b> Log </b></summary>

```java

STDOUT: Dec 11, 2023 3:47:33 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.8; freeplane_xml_version = freeplane 1.11.5
git revision = 297aad4e0654f3a02747f1cd8ebd65de97306889 dpolivaev 2023-11-12T20:46:51Z
java_version = 17.0.6; os_name = Windows 11; os_version = 10.0
...

...
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.util.NoSuchElementException
STDERR: at org.freeplane.core.util.collection.SortedMapVector.getValue(SortedMapVector.java:136)
STDERR: at org.freeplane.features.attribute.AttributeRegistry.getElement(AttributeRegistry.java:187)
STDERR: at org.freeplane.features.attribute.mindmapmode.MAttributeController.performInsertRow(MAttributeController.java:653)
STDERR: at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:133)
STDERR: at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1049)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1026)
STDERR: at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
STDERR: at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
STDERR: at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1367)
STDERR: at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)
STDERR: at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
STDERR: at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1350)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:524)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicTableUI$Actions.actionPerformed(BasicTableUI.java:525)
STDERR: at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
STDERR: at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
STDERR: at java.desktop/javax.swing.JTable.processKeyBinding(JTable.java:5321)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.processKeyBinding(AttributeTable.java:784)
STDERR: at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3009)
STDERR: at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6403)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2266)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null
STDERR: at org.freeplane.features.attribute.NodeAttributeTableModel.getAttribute(NodeAttributeTableModel.java:120)
STDERR: at org.freeplane.features.attribute.mindmapmode.MAttributeController.performSetValueAt(MAttributeController.java:815)
STDERR: at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:125)
STDERR: at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1049)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1026)
STDERR: at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
STDERR: at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
STDERR: at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1353)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:524)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.focusLost(AttributeSelectionChangeListener.java:69)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.propertyChange(AttributeSelectionChangeListener.java:88)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:784)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:664)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null
STDERR: at org.freeplane.features.attribute.NodeAttributeTableModel.getAttribute(NodeAttributeTableModel.java:120)
STDERR: at org.freeplane.features.attribute.mindmapmode.MAttributeController.performSetValueAt(MAttributeController.java:815)
STDERR: at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:125)
STDERR: at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1049)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1026)
STDERR: at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
STDERR: at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
STDERR: at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1353)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:524)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.focusLost(AttributeSelectionChangeListener.java:69)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.propertyChange(AttributeSelectionChangeListener.java:88)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:784)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:664)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null
STDERR: at org.freeplane.features.attribute.NodeAttributeTableModel.getAttribute(NodeAttributeTableModel.java:120)
STDERR: at org.freeplane.features.attribute.mindmapmode.MAttributeController.performSetValueAt(MAttributeController.java:815)
STDERR: at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:125)
STDERR: at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1049)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1026)
STDERR: at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
STDERR: at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
STDERR: at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1353)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:524)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.getCellEditor(AttributeTable.java:497)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.getCellEditor(AttributeTable.java:485)
STDERR: at java.desktop/javax.swing.JTable.editCellAt(JTable.java:3563)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editCellAt(AttributeTable.java:359)
STDERR: at java.desktop/javax.swing.JTable.editCellAt(JTable.java:3523)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.insertRow(AttributeTable.java:646)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.insertRow(AttributeTable.java:639)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeView.addRow(AttributeView.java:340)
STDERR: at org.freeplane.view.swing.map.attribute.AttributePanelManager$TableCreator$1.actionPerformed(AttributePanelManager.java:113)
STDERR: at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
STDERR: at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
STDERR: at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
STDERR: at java.desktop/javax.swing.plaf.basic.BasicButtonListener.focusLost(BasicButtonListener.java:222)
STDERR: at java.desktop/java.awt.Component.processFocusEvent(Component.java:6518)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6382)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2266)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1070)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:738)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.SentEvent.dispatch(SentEvent.java:75)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:261)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:288)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:808)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.SequencedEvent.dispatch(SequencedEvent.java:206)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
STDERR: at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null
STDERR: at org.freeplane.features.attribute.NodeAttributeTableModel.getAttribute(NodeAttributeTableModel.java:120)
STDERR: at org.freeplane.features.attribute.mindmapmode.MAttributeController.performSetValueAt(MAttributeController.java:815)
STDERR: at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:125)
STDERR: at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1049)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1026)
STDERR: at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
STDERR: at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
STDERR: at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1353)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:524)
STDERR: at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
STDERR: at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.focusLost(AttributeSelectionChangeListener.java:69)
STDERR: at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.propertyChange(AttributeSelectionChangeListener.java:88)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
STDERR: at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
STDERR: at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:784)
STDERR: at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:664)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

**Comment by dpolivaev** [comment]
Preview 1.11.9_04
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
