### ISSUE TITLE
FP v.1.11.9_01:  connector with one node not visible throws error

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#1587]
**Describe the bug**
When having a connector connecting nodes of  different branches, if one branch get folded, then it throws an error.

example:
![image](https://github.com/freeplane/freeplane/assets/35700575/01998a9e-68fc-4dfc-b9fb-5c7e20b09c64)
[FPv1.11.9_01 connector error.zip](https://github.com/freeplane/freeplane/files/13675753/FPv1.11.9_01.connector.error.zip)

----

**To Reproduce**
1. in a mindmap add a connector between nodes from diferent parents (or branches)
3. fold one of the node's ancestor, so it is not visible anymore

-----
**Log**
```groovy
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "org.freeplane.view.swing.map.NodeView.getMainView()" because "targetView" is null
STDERR: at org.freeplane.view.swing.map.MapView.isConnectorVisibleOnView(MapView.java:2134)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2094)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2164)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2188)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2188)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2188)
STDERR: at org.freeplane.view.swing.map.MapView.paintConnectors(MapView.java:2157)
STDERR: at org.freeplane.view.swing.map.MapView.paintChildren(MapView.java:2032)
STDERR: at org.freeplane.view.swing.map.MapView.paintChildren(MapView.java:2015)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at org.freeplane.view.swing.map.MapView.paint(MapView.java:1942)
STDERR: at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
STDERR: at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
STDERR: at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
STDERR: at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
STDERR: at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5081)
STDERR: at org.freeplane.view.swing.map.MainView.paintFoldingRectangleImmediately(MainView.java:788)
STDERR: at org.freeplane.view.swing.map.MainView.setMouseArea(MainView.java:776)
STDERR: at org.freeplane.view.swing.ui.DefaultNodeMouseMotionListener.mouseMoved(DefaultNodeMouseMotionListener.java:230)
STDERR: at org.freeplane.view.swing.ui.mindmapmode.MNodeMotionListener.mouseMoved(MNodeMotionListener.java:182)
STDERR: at org.freeplane.view.swing.ui.DefaultNodeMouseMotionListener.mouseEntered(DefaultNodeMouseMotionListener.java:192)
STDERR: at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:308)
STDERR: at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:307)
STDERR: at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
STDERR: at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
STDERR: at org.freeplane.view.swing.map.MainView.processMouseEvent(MainView.java:699)
STDERR: at java.desktop/java.awt.Component.processEvent(Component.java:6391)
STDERR: at java.desktop/java.awt.Container.processEvent(Container.java:2266)
STDERR: at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
STDERR: at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4726)
STDERR: at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4704)
STDERR: at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4555)
STDERR: at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
STDERR: at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
STDERR: at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
STDERR: at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
STDERR: at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by EdoFro** [comment]
I build it and tested. 
Works ok now 👍🏼 

I won't close this issue until the new preview version is released, ( to avoid report duplication if somebody has the same Issue)
