### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by cpahk** [freeplane/freeplane#1602]
![微信图片_20231226164226](https://github.com/freeplane/freeplane/assets/154876638/f4a02682-4a61-4b22-9a89-5f4d7c8c019e)
at 2023-12-26 08:41:33 CMT,  hash 6929487ea21236ebca25921b0482a4d6
previous report : no reports sent before
freeplane_version = 1.11.8; freeplane_xml_version = freeplane 1.11.5
git revision = 297aad4e0654f3a02747f1cd8ebd65de97306889 dpolivaev 2023-11-12T20:46:51Z
java_version = 15.0.10; os_name = Windows 10; os_version = 10.0
Exception in thread "AWT-EventQueue-0" 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    groovy/lang/GroovyClassLoader.getPermissions(Ljava/security/CodeSource;)Ljava/security/PermissionCollection; @62: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/security/PermissionCollection'
  Current Frame:
    bci: @62
    flags: { }
    locals: { 'groovy/lang/GroovyClassLoader', 'java/security/CodeSource', 'java/lang/Object', 'java/security/ProtectionDomain', 'java/security/PermissionCollection', 'java/util/Enumeration' }
    stack: { 'java/lang/Object', 'java/security/Permission' }
  Bytecode:
    0000000: 2a2b b702 1d4d a700 0c4e bb02 1f59 b702
    0000010: 204d 2ab7 0224 4e2d b602 293a 0419 04c6
    0000020: 0025 1904 b602 2f3a 0519 05b9 0234 0100
    0000030: 9900 142c 1905 b902 3701 00c0 0239 b602
    0000040: 3da7 ffe8 a700 0c4e bb02 1f59 b702 204d
    0000050: 2cb6 0240 2cb0                         
  Exception Handler Table:
    bci [0, 6] => handler: 9
    bci [0, 68] => handler: 71
  Stackmap Table:
    same_locals_1_stack_item_frame(@9,Object[#539])
    append_frame(@18,Object[#256])
    append_frame(@41,Object[#550],Object[#555],Object[#561])
    chop_frame(@68,1)
    full_frame(@71,{Object[#2],Object[#176]},{Object[#282]})
    append_frame(@80,Object[#256],Object[#256])

	at org.freeplane.plugin.script.ClasspathScriptCompiler.<init>(ClasspathScriptCompiler.java:55)

	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:181)

	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:27)

	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:256)

	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:272)

	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:62)

	at org.freeplane.main.osgi.ActivatorImpl$1.run(ActivatorImpl.java:196)

	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.base/java.security.AccessController.doPrivileged(Unknown Source)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

[常见故障判断处理拓扑.zip](https://github.com/freeplane/freeplane/files/13770105/default.zip)

**Comment by dpolivaev** [comment]
How often does it happen?

**Comment by cpahk** [comment]
After installation, use and saving, it frequently appears when closing and opening again, and cannot be opened and used normally again.

**Comment by cpahk** [comment]
And the startup page is stuck on the desktop and cannot be closed, even in the task manager.
![20231227084652](https://github.com/freeplane/freeplane/assets/154876638/ec818654-6a1c-44f6-b61e-2122ca88f921)

**Comment by dpolivaev** [comment]
I have updated some dependencies in the latest preview https://sourceforge.net/projects/freeplane/files/freeplane%20preview/ and it might solve the issue, but it is not very likely.

1. Please try the latest preview.
2. If it does not solve the issue, please zip all files and directories that you find in the "user directory" right after the start failure and upload them here so that I can have a closer look. The Freeplane user directory can be found by invoking the menu item Tools->Open user directory. Its default  location for Windows is the directory 1.11.x in %APPDATA%\Freeplane

It looks like you are not the only one user seeing the bug, but the majority of the users do not see it.

**Comment by Reiziuh** [comment]
Hi. dplolivaev. I have the same/similar problem. I tried to reinstall it several times, but only the first time after each reinstallation it worked well, but the second time won't work. I have to terminate the Java process to stop the app. I tried the 1.12.2 preview, but it doesn't work either. 
![image](https://github.com/user-attachments/assets/fbdedaf9-b9cd-4706-89db-66e191f5d9de)
[1.11.x.zip](https://github.com/user-attachments/files/16411676/1.11.x.zip)

**Comment by Reiziuh** [comment]
I found the reason. It conflicts with 360 antivirus software. 360 says it "auto-blocks" Freeplane's "emulate keystrokes activities." Turning off 360 or uninstalling it will solve the problem. This wastes me a whole afternoon. Thanks anyway. Have a nice day!
