### ISSUE TITLE
Freeplane crash on open - java.lang.NullPointerException exception

### ISSUE THREAD

**Issue by fschiro** [freeplane/freeplane#1678]
**Describe the bug**
When I open freeplane it crashes. When I first installed it, it worked fine, but after two days without using it, now it crashes every time I opened. I also tried uninstall and reinstall but I get the same error. 

I had to downgrade to 1.11.8 to get the program to open. 

```bash
at 2024-02-05 12:09:05 CMT,  hash 250729c563bb62177f8c532fa0e667f5
previous report : no reports sent before
freeplane_version = 1.11.10; freeplane_xml_version = freeplane 1.11.5
git revision = 4f3abb16eb364b5e520b02ec6cb8dde52417e666 dpolivaev 2024-01-22T17:02:25Z
java_version = 11.0.21; os_name = Linux; os_version = 6.6.10-76060610-generic
Exception in thread "AWT-EventQueue-0" 
java.lang.NullPointerException
	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.fromJsonFile(CodeExplorerConfigurations.java:79)
	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.loadConfigurations(CodeExplorerConfigurations.java:72)
	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.loadConfigurations(CodeExplorerConfigurations.java:65)
	at org.freeplane.plugin.codeexplorer.configurator.CodeProjectController.<init>(CodeProjectController.java:61)
	at org.freeplane.plugin.codeexplorer.CodeModeController.<init>(CodeModeController.java:35)
	at org.freeplane.plugin.codeexplorer.CodeModeControllerFactory.createModeController(CodeModeControllerFactory.java:55)
	at org.freeplane.plugin.codeexplorer.Activator$1.installExtension(Activator.java:38)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:271)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:307)
	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:66)
	at org.freeplane.main.osgi.ActivatorImpl$2.run(ActivatorImpl.java:230)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Install Freeplane `sudo dpkg -i freeplane_1.11.10~upstream-1_all.deb`
2. Try to open application, it crashes and sends bug report
3. Uninstall freeplane `sudo dpkg -P freeplane`
4. Reinstall, same error/crash report

**Expected behavior**
Application opens

**Mind map files**
Don't get a chance to open mindmap file

**Desktop (please complete the following information):**
 - Ubuntu 22.04
```bash
java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

**Comment by dpolivaev** [comment]
Thanks for letting me know.

Please try the following: in the Freeplane user configuration directory find file codeExplorer.json, upload it here zipped so that I can have a look and delete it.

**Comment by fschiro** [comment]
I just looked at the file `/home/frank/.config/freeplane/1.11.x/codeExplorer.json` and it is 0 bytes empty file. Unsure why, I never touched the file. I did however downgrade freeplane with `sudo dpkg -P freeplane` before reinstalling earlier version, unsure if that has anything to do with file being empty.

**Comment by dpolivaev** [comment]
All right, just delete the empty file

**Comment by wxtsxt** [comment]
I had same problem on windows. Removing `C:\Users\{{user}}\AppData\Roaming\Freeplane\1.11.x\codeExplorer.json` fixed the problem

**Comment by dpolivaev** [comment]
I hope it is fixed in Freeplane 1.11.11 released now

**Comment by Dmytro-Shulha** [comment]
Had seemingly same NullPointerException when trying to start freeplane v1.11.14, v1.12.2-alpha, and v1.9.14.
Windows 11 Pro 23H2 OS build 22631.3737
To me, it was most probably due to my username directory having cyrilic symbols.
Or may it be some permissions issues with User/AppData/Roaming/Freeplane directory? Not sure.

I was able to workaround this issue by starting freeplane from the terminal with custom user directory:
`echo 'PATH="$PATH:/c/Program Files/Freeplane"' >> ~/.bashrc`
restart terminal
`freeplane -U /d/another/directory`

Is there any way to change user directory from Freeplane settings, or in some config file, so I won't need to start it from terminal each time?

---

Also, there is an option to set user directory in a Windows shortcut:
![image](https://github.com/freeplane/freeplane/assets/48155493/e88823c9-2d64-4808-937b-92501ed70e98)


---

Actual exception:

```
at 2024-06-22 21:24:49 CMT,  hash 0647ecaf83cbb0b150fbfc1fac6b2966
previous report : no reports sent before
freeplane_version = 1.11.14; freeplane_xml_version = freeplane 1.11.5
git revision = 9f7e8ed5c5f1d6a40abb6aa7bd761feebe600094 dpolivaev 2024-05-14T08:16:57Z
java_version = 15.0.10; os_name = Windows 11; os_version = 10.0
Can not read addon directory C:\Users\Р”РјРёС‚СЂРѕ\AppData\Roaming\Freeplane\1.11.x\addons
Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at org.freeplane.plugin.script.ScriptingRegistration.registerScriptAddOns(ScriptingRegistration.java:262)
	at org.freeplane.plugin.script.ScriptingRegistration.register(ScriptingRegistration.java:179)
	at org.freeplane.plugin.script.Activator$1.installExtension(Activator.java:27)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:291)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:307)
	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:66)
	at org.freeplane.main.osgi.ActivatorImpl$2.run(ActivatorImpl.java:230)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
