### ISSUE TITLE
Cannot open freeplane

### ISSUE THREAD

**Issue by nasbhuiyan** [freeplane/freeplane#1711]
**Describe the bug**
Cannot open freeplane. Shows up with an error page. Have restarted the program, uninstalled and reinstalled and restarted my computer and updated the OS. Still cannot open the program. 

**To Reproduce**
Just clicking on the icon on desktop will brung up bug report. 

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Bug report**
at 2024-03-01 03:40:24 CMT,  hash 4bec9c1ed014fb7cbff3ce3276f22b96
previous report : no reports sent before
freeplane_version = 1.11.10; freeplane_xml_version = freeplane 1.11.5
git revision = 4f3abb16eb364b5e520b02ec6cb8dde52417e666 dpolivaev 2024-01-22T17:02:25Z
java_version = 15.0.10; os_name = Windows 11; os_version = 10.0
Exception in thread "AWT-EventQueue-0" 
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "configurations" is null

	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.fromJsonFile(CodeExplorerConfigurations.java:79)

	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.loadConfigurations(CodeExplorerConfigurations.java:72)

	at org.freeplane.plugin.codeexplorer.task.CodeExplorerConfigurations.loadConfigurations(CodeExplorerConfigurations.java:65)

	at org.freeplane.plugin.codeexplorer.configurator.CodeProjectController.<init>(CodeProjectController.java:61)

	at org.freeplane.plugin.codeexplorer.CodeModeController.<init>(CodeModeController.java:35)

	at org.freeplane.plugin.codeexplorer.CodeModeControllerFactory.createModeController(CodeModeControllerFactory.java:55)

	at org.freeplane.plugin.codeexplorer.Activator$1.installExtension(Activator.java:38)

	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:271)

	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:307)

	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:66)

	at org.freeplane.main.osgi.ActivatorImpl$2.run(ActivatorImpl.java:230)

	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)

	at java.base/java.security.AccessController.doPrivileged(Unknown Source)

	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)

	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by StarFangDragon** [comment]
I just had the same problem, and manually reinstalling with version 1.11.11 seems to have fixed it.

**Comment by HaaiHenkie** [comment]
I had this same problem when downgrading for v1.11.11 to v1.11.10. You probably did a similar downgrade. The problem is with the file `codeExplorer.json`. Freeplane v1.11.11 leaves this file empty while v1.11.10 needs een empty list indicated by enclosing square hooks: `[]`. You can solve this by deleting `codeExplorer.json` or by editing it to add the square hooks. I think this is a bug because v1.11.11 is not a major new release so the contents of the Freeplane user directory should be backwards compatible with the previous version.

**Comment by HaaiHenkie** [comment]
Same as #1678
