### ISSUE TITLE
Bug if tag exceeds node max width

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1776]
Steps:
- create a tag that exceeds the node max width:
![image](https://github.com/freeplane/freeplane/assets/77707706/f3a9058f-332e-4b6d-a724-52bb46517532)

- double the node to try to edit node core. Error message shows up, with this log:

```
STDERR: abr. 08, 2024 11:01:30 AM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: bad position: -1
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1689)
	at org.freeplane.view.swing.map.mindmapmode.EditNodeTextField.show(EditNodeTextField.java:908)
	at org.freeplane.features.text.mindmapmode.MTextController.edit(MTextController.java:1114)
	at org.freeplane.features.text.mindmapmode.MTextController.edit(MTextController.java:1073)
	at org.freeplane.features.text.mindmapmode.MTextController.edit(MTextController.java:815)
	at org.freeplane.view.swing.ui.mindmapmode.MNodeMotionListener.mouseClicked(MNodeMotionListener.java:161)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6660)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at org.freeplane.view.swing.map.MainView.processMouseEvent(MainView.java:699)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4592)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Example map: 
[tag bug.zip](https://github.com/freeplane/freeplane/files/14906549/tag.bug.zip)

1.12.1 alpha

**Comment by euu2021** [comment]
Maybe, truncation of the tag text is necessary?

**Comment by euu2021** [comment]
> Maybe, truncation of the tag text is necessary?

Or, maybe, a line break in the tag.

**Comment by dpolivaev** [comment]
Preview 1.12.1_02
