### ISSUE TITLE
FP 1.12.01_01: missing Day attribute in nodes - no possible to activate this release

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1780]
**Describe the bug**
Quite all of the nodes with attributes missed the Day attribute and its values, in the obfuscated map you can notice that quite all of the nodes (with attributes) that must have the Day attribute, those nodes are missing it, just exceptions are 2 nodes highlighted with a blue right arrow that have the full attribute serie and are working correctly.
Normally the structure of this map branch is to have a node with the Day attribute and a date value or to have a formula reading the min Date attribute of its children in the Day attribute value.
It seems that then opening the map in FP 1.12.1_01 most (but not all) of the nodes have the Day attribute cancelled

If I unistall FP 1.12.1_01 and install the previous 1.11.12_08 everything is working but I have to rewrite manually all of the missing Day attributes and the map is stable.

Therefore I cannot use this new FP release....

*

**Mind map files**
[myLab try1~obfuscated.zip](https://github.com/freeplane/freeplane/files/14962951/myLab.try1.obfuscated.zip)
[log.zip](https://github.com/freeplane/freeplane/files/14962952/log.zip)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - Java Version FP embedded in 1.12.1_01

**Additional context**
1) I experienced the same problem as above in another pc W10 same FP release
2) Beyond this topic after trying to open in the release the maps I experienced delays, flashing, strange behaviours, I think because of the error generated by this missing attribute...

**Comment by dpolivaev** [comment]
I am sorry I do not understand what you mean.
The attached map behaves similarly on the Freeplane versions 1.11.12_08, 1.11.12, and with my latest code on branch 1.12.x.
I would appreciate it if you could create a minimum mind map where I can see the problem and explain what exactly I should pay attention to.

**Comment by dpolivaev** [comment]
1.11.12_08:
<img width="377" alt="1 11 12_08" src="https://github.com/freeplane/freeplane/assets/1558052/a47d2a10-ac36-40a3-8dde-312f7b26b58b">

1.12.1_latest:
<img width="334" alt="1 12 x_latest" src="https://github.com/freeplane/freeplane/assets/1558052/b6fe1d18-f113-4178-8c43-755be6e3531a">

**Comment by Illegit** [comment]
![Screenshot 2024-04-13 165843](https://github.com/freeplane/freeplane/assets/62674157/d85ceeb9-5665-476c-95f6-648821e3fe0c)
[attributeFailFP11201_01.zip](https://github.com/freeplane/freeplane/files/14967739/attributeFailFP11201_01.zip)
Here above the map as I read it after eliminating all the other nodes, this was possible only after reinstalling FP 1.11.12_08, because in the FP1.12.1_01 there were too many disruptions. Now I will correct this map reinserting the Day attribute.

[attributeFailFP11201_01 v2.zip](https://github.com/freeplane/freeplane/files/14967765/attributeFailFP11201_01.v2.zip)
The v2 is the previous map with the Day attribute inside the nodes.

after installing FP1.12.1_01:
[attributeFailFP11201_01 v3.zip](https://github.com/freeplane/freeplane/files/14967782/attributeFailFP11201_01.v3.zip)
this is the resulting map with the same errors.
[log.zip](https://github.com/freeplane/freeplane/files/14967785/log.zip)
this is the corresponding log file
![Screenshot 2024-04-13 172128](https://github.com/freeplane/freeplane/assets/62674157/f0e316fd-c5d5-4004-8df6-8b38c6e99bcc)
 Hope this is helping, otherwise I need you guide me in what you need to see.

Conclusion: for an unknown reason seems that when opening the files with the new release these files are partially deprived by the dates in attributes.

Wait for your feedback.

**Comment by i-plasm** [comment]
Hi @Illegit , I was able to check your maps, and in particular the map  at ***attributeFailFP11201_01 v3.zip*** behaves badly as you described. The errors are mostly of the type

```
SEVERE: Can not process elementattribute
java.lang.ClassCastException: class org.freeplane.features.format.FormattedFormula cannot be cast to class java.lang.Comparable (org.freeplane.features.format.FormattedFormula is in unnamed module of loader org.knopflerfish.framework.BundleClassLoader @6bec5420; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.base/java.util.Collections.indexedBinarySearch(Unknown Source)
	at java.base/java.util.Collections.binarySearch(Unknown Source)
	at org.freeplane.core.util.collection.SortedComboBoxModel.binarySearch(SortedComboBoxModel.java:62)
	at org.freeplane.core.util.collection.SortedComboBoxModel.addImpl(SortedComboBoxModel.java:53)
	at org.freeplane.core.util.collection.SortedComboBoxModel.add(SortedComboBoxModel.java:48)
	at org.freeplane.features.attribute.AttributeRegistryElement$RegisteredAttributeValues._add(AttributeRegistryElement.java:37)
	at org.freeplane.features.attribute.AttributeRegistryElement.addValue(AttributeRegistryElement.java:90)
	at org.freeplane.features.attribute.AttributeRegistry.registry(AttributeRegistry.java:272)
...
```

which is similar to my bug report from yesterday, which also lists the following call in the stack trace very close to the production of the exception `at org.freeplane.core.util.collection.SortedComboBoxModel.binarySearch(SortedComboBoxModel.java:62)`

I also saw `Null pointer returned by formula`  errors, but that would be a consequence of the fact that the "Day" or "Date" values fail to be loaded for so many nodes, and those formulas depend on such values.

So, your issues may be a consequence of the bug I posted yesterday https://github.com/freeplane/freeplane/issues/1781, at least in part. My suggestion is to wait until @dpolivaev  publishes the next preview/release and test your maps again. However, I saw some extra errors that may be of a different nature - not sure- :


## UI Freezes on Error `Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null`

To reproduce this error, open the map  at ***attributeFailFP11201_01 v3.zip*** and insert a new node and there insert a new attribute inline, giving it the name "Day" (using exact letters capitalization). Suddenly the MapView will crash and most node/map UI functions will become non-responsive, and Freeplane must be restarted. Logged error:

```
SEVERE: Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException: Cannot invoke "java.util.Vector.get(int)" because "this.attributes" is null
	at org.freeplane.features.attribute.NodeAttributeTableModel.getAttribute(NodeAttributeTableModel.java:145)
	at org.freeplane.features.attribute.mindmapmode.MAttributeController.performSetValueAt(MAttributeController.java:816)
	at org.freeplane.view.swing.map.attribute.ExtendedAttributeTableModelDecorator.setValueAt(ExtendedAttributeTableModelDecorator.java:125)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2787)
	at org.freeplane.view.swing.map.attribute.AttributeTable.setValueAt(AttributeTable.java:1087)
	at org.freeplane.view.swing.map.attribute.AttributeTable.editingStopped(AttributeTable.java:1064)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
	at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:159)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.actionPerformed(DefaultCellEditor.java:392)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
	at java.desktop/javax.swing.JComboBox.actionPerformed(JComboBox.java:1353)
	at org.freeplane.view.swing.map.attribute.AttributeTable$3.actionPerformed(AttributeTable.java:552)
	at java.desktop/javax.swing.DefaultCellEditor$3.stopCellEditing(DefaultCellEditor.java:156)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.focusLost(AttributeSelectionChangeListener.java:69)
	at org.freeplane.view.swing.map.attribute.AttributeSelectionChangeListener.propertyChange(AttributeSelectionChangeListener.java:88)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:784)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:664)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.dispatchAndCatchException(KeyboardFocusManager.java:2599)
	at java.desktop/java.awt.KeyboardFocusManager.processCurrentLightweightRequests(KeyboardFocusManager.java:2695)
	at java.desktop/java.awt.KeyboardFocusManager.retargetFocusEvent(KeyboardFocusManager.java:2944)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4874)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
``` 

## Error `No enum constant org.freeplane.api.ChildNodesLayout.AUTO_BYFIRSTCHILD`:

```
SEVERE: Can not process attribute CHILD_NODES_LAYOUT = 'AUTO_BYFIRSTCHILD'
java.lang.IllegalArgumentException: No enum constant org.freeplane.api.ChildNodesLayout.AUTO_BYFIRSTCHILD
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.freeplane.api.ChildNodesLayout.valueOf(ChildNodesLayout.java:11)
	at org.freeplane.features.layout.LayoutBuilder$1.setAttribute(LayoutBuilder.java:42)
	at org.freeplane.core.io.xml.TreeXmlReader.addAttribute(TreeXmlReader.java:110)
	...
```

Kind regards

**Comment by Illegit** [comment]
Thanks, as I have a moment I'll correct the auto_byfirstchild (I do not know why I found it everywhere in my maps...).

**Comment by dpolivaev** [comment]
Preview 1.12.1_02 is likely to fix your issue because I think it is related to #1781

**Comment by Illegit** [comment]
I confirm. It is working nicely. Very appreciated. Thank you.
