### ISSUE TITLE
Tags: error when trying to rename tag

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1870]
- create a new map
- create tag zzz
- open `Edit->Node properties->Manage tag categories for map`
- try to rename zzz to zzz2. Error happens, with this log:

[log.txt](https://github.com/user-attachments/files/15858056/log.txt)

Example map, after doing the steps above, a new tag zzz2 was created, but the zzz tag was not replaced:
[EXAMPLE bug tag.zip](https://github.com/user-attachments/files/15858058/EXAMPLE.bug.tag.zip)

Preview 1.12.2-01 alpha

**Comment by euu2021** [comment]
Also, when adding a tag directly inside `Edit->Node properties->Manage tag categories for map`, it's not possible to give a name to this new tag.

**Comment by dpolivaev** [comment]
1.12.2_02

**Comment by euu2021** [comment]
I'm still getting the error:

<details>

```
STDERR: jun 16, 2024 5:09:41 PM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.util.NoSuchElementException
	at java.util.TreeMap.key(Unknown Source)
	at java.util.TreeMap$NavigableSubMap.firstKey(Unknown Source)
	at org.freeplane.features.icon.TagCategories.replaceReferencedTags(TagCategories.java:533)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.apply(TagCategoryEditor.java:405)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.submit(TagCategoryEditor.java:1004)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$new$0(TagCategoryEditor.java:541)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

**Comment by dpolivaev** [comment]
Preview 1.12.2_03 alpha

**Comment by euu2021** [comment]
The problem still happens in some renaming situations. I will explain, tomorrow.

**Comment by euu2021** [comment]
For example, in this map, try to rename xxx::222 to xxx::222b:

[EXAMPLE bug tags2.zip](https://github.com/user-attachments/files/15894229/EXAMPLE.bug.tags2.zip)

I get this error:

<details>

```
STDERR: jun 18, 2024 10:25:35 PM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.freeplane.core.util.collection.SortedComboBoxModel.getElementAt(SortedComboBoxModel.java:115)
	at org.freeplane.features.icon.TagCategories.removeTagsAndCategories(TagCategories.java:599)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.addReplacement(TagCategoryEditor.java:368)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.valueForPathChanged(TagCategoryEditor.java:361)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.valueForPathChanged(TagCategoryEditor.java:321)
	at org.freeplane.features.icon.TagCategories$TagCategoryTree.valueForPathChanged(TagCategories.java:70)
	at javax.swing.plaf.basic.BasicTreeUI.completeEditing(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.editingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagCellEditor.stopCellEditing(TagCategoryEditor.java:203)
	at javax.swing.plaf.basic.BasicTreeUI.stopEditing(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
</details>

**Comment by dpolivaev** [comment]
Preview 1.12.2_04 alpha

**Comment by euu2021** [comment]
In this map, try to rename xxx::yyy::3 to xxx::yyy2::3


[EXAMPLE bug tag cat (2).zip](https://github.com/user-attachments/files/15936551/EXAMPLE.bug.tag.cat.2.zip)



This error happens:

<details>

```
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
	at java.util.ArrayList.addAll(Unknown Source)
	at org.freeplane.features.icon.TagCategories.replaceReferencedTags(TagCategories.java:545)
	at org.freeplane.features.icon.TagCategories.replaceReferencedTags(TagCategories.java:528)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.apply(TagCategoryEditor.java:406)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.submit(TagCategoryEditor.java:1005)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$new$0(TagCategoryEditor.java:542)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
</details>

**Comment by dpolivaev** [comment]
Preview 1.12.2_05

Thanks a lot, it is great to have you as a tester

**Comment by euu2021** [comment]
Another one:
- create a new map
- add tag xxx::111 using `Edit->Node properties->Edit tags`
- inside `Edit->Node properties->Manage tag categories for map`, rename xxx::111 to xxx2::111

This error happens:

<details>

```
STDERR: jun 23, 2024 10:05:37 AM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
	at java.util.ArrayList.addAll(Unknown Source)
	at org.freeplane.features.icon.TagCategories.replaceReferencedTags(TagCategories.java:549)
	at org.freeplane.features.icon.TagCategories.replaceReferencedTags(TagCategories.java:528)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.apply(TagCategoryEditor.java:410)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.submit(TagCategoryEditor.java:1009)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$new$0(TagCategoryEditor.java:546)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```
</details>

**Comment by dpolivaev** [comment]
Thanks

Preview 1.12.2_06.

**Comment by euu2021** [comment]
I did more tests and I see no more problems. Thanks
