### ISSUE TITLE
Tags: categorized tag also shows up as uncategorized

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1905]
In the example map, I created the tag xxx and also other tags like xxx::111. The tag xxx appeared also as Uncategorized Tags:

![image](https://github.com/freeplane/freeplane/assets/77707706/69b2e199-8109-409e-879f-6c825fac75d4)

[EXAMPLE bug tags cat 2.zip](https://github.com/user-attachments/files/16045144/EXAMPLE.bug.tags.cat.2.zip)

Try to rename any of the xxx tags and an error happens:

<details>
```
STDERR: jun 30, 2024 11:57:08 AM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:469)
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:396)
	at org.freeplane.features.icon.TagCategories.registerTagReferenceIfUnknown(TagCategories.java:651)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$submit$5(TagCategoryEditor.java:1007)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.submit(TagCategoryEditor.java:1007)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$new$0(TagCategoryEditor.java:553)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

freeplane_bin-1.12.2-alpha-pre07

**Comment by dpolivaev** [comment]
Preview 1.12.2_08

**Comment by euu2021** [comment]
In the same example map, if I first rename one of the tags, press ok, reopen the Tag Manager, and rename the other tag, I get an error:
![image](https://github.com/freeplane/freeplane/assets/77707706/b26ca259-a4e1-4868-8afb-82194b121561)

<details>
```
STDERR: jul 06, 2024 9:30:58 PM org.freeplane.core.util.LogUtils severe
GRAVE: Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:470)
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:397)
	at org.freeplane.features.icon.TagCategories.registerTagReferenceIfUnknown(TagCategories.java:655)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$submit$5(TagCategoryEditor.java:1012)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.submit(TagCategoryEditor.java:1012)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor.lambda$new$0(TagCategoryEditor.java:554)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
</details>

freeplane-1.12.2-alpha-pre08

**Comment by dpolivaev** [comment]
Thank you for reporting. I do not understand what you do. Your report is too short. I need to reproduce each and every action. And I would appreciate it if you could open a new bug report because having more than one issue in one bug report confuses me even more.

Think. I get to Freeplane once a week and I am very sad that we loose so much time because of I just do not get what you did.
