### ISSUE TITLE
Error: Renaming categories or uncategorized tags fails, causing data loss and tags definition inconsistency

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2017]
**Describe the bug**
I've found a bug (2 variations) that makes it impossible to rename tags/categories, and causes 1) tag data loss, and 2) map tags definition inconsistency. It's really troublesome because it might not be readily apparent so the user will likely remain unaware and lose data after saving the mindmap, and also end up with a corrupt/inconsistent map tags definition.

**To Reproduce**
## Variation 1: Category data loss

1. Create a new mind map
1. Add this tag to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `cat1::tag1`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Select `cat1` and rename it to `zzz`
1. Click OK
1. On the root node right click and choose `Edit -> Edit tags`
1. =>>> ERROR: Notice the rename of category to `zzz` was ignored, and the outdated tag `cat1::tag1` remains
1. Click 'OK' and notice that an error is thrown and logged (full logged exception at the end). If the map is saved after following the previous steps, then we will have a map with a corrupt map tags listing (specifically, the map will have "orphan" tags, that is, tags that appear on nodes but that are not registered in the map tags definition, and of course, nodes with outdated tags/categories). 
	~~~
	SEVERE: Exception in thread "AWT-EventQueue-0"
	java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
		at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
		at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
		at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
		at java.base/java.util.Objects.checkIndex(Objects.java:359)
		at java.base/java.util.ArrayList.get(ArrayList.java:427)
		at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:482)
		at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:471)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	...
	~~~
	

# Variation 2: Uncategorized tag data loss

1. Create a new mind map
1. Add this tag to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `tag1`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Select `tag1` and rename it to `yyy`
1. Click OK
1. =>>> ERROR: Notice the rename to `yyy` was ignored, and the outdated tag remains. No exception is thrown/logged, so user is unaware. If the map is saved after following the previous steps, then we will have a map with a corrupt map tags listing (specifically, the map will have "orphan" tags, that is, tags that appear on nodes but that are not registered in the map tags definition, and of course, nodes with outdated tags/categories). 

**Expected behavior**
The changes performed from the Categories Manager should have been applied. Also, after saving the map, the map tags definition should have listed all existing tags (so there are no "orphan" tags, i.e tags used by nodes but not listed in the map tags definition)

**Desktop (please complete the following information):**
 - Freeplane1.12.5 stable

**Logs** 

## Variation 1 Log

~~~
SEVERE: Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:482)
	at org.freeplane.features.icon.TagCategories.registerTagReference(TagCategories.java:471)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.freeplane.features.icon.mindmapmode.MIconController.setTags(MIconController.java:622)
	at org.freeplane.features.icon.mindmapmode.TagEditor.submit(TagEditor.java:737)
	at org.freeplane.features.icon.mindmapmode.TagEditor.lambda$new$0(TagEditor.java:389)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
~~~

**Comment by dpolivaev** [comment]
Preview 1.12.6_02
I have even written some regression tests

**Comment by i-plasm** [comment]
Thanks Dimitry 👍. I'll try to test manually against the old bugs as soon as I have free time.

**Comment by dpolivaev** [comment]
@i-plasm  I would like to release the fixes. But in the past I have multiple times experienced that I got your bug reports within a few hours after I released a new stable version. Therefore I decided to wait until your green light although I think that current bugs in stable are quite bad.

**Comment by i-plasm** [comment]
Hello Dimitry. Last few weeks have been quite demanding for me. I actually planned to start re-testing today. I hope to share feedback today or tomorrow.

**Comment by dpolivaev** [comment]
Thanks. Please use the preview version released today.
