### ISSUE TITLE
It is not possible to merge categorized tags

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2032]
**Describe the bug**
It is not possible to merge categorized tags

**To Reproduce**
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `cat::tag1`
   - `cat::tag2`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree
1. Merge both tags into one by changing the name of `tag1` to `tag2`
1. Click OK.
1. =>>> ERROR: Notice the merge failed - both `tag1` and `tag2` still shown in the root node.
1. Right click on the root node and choose `Edit -> Edit tags`
1. =>>> ERROR: an exception is thrown (see log at the end). 
1. EXTRA INFO: 
   - The same issues described above happen if we had attempted to merge `aaa::bbb::ccc` and `aaa::ddd::ccc` by renaming `bbb` to `ddd`
   - The issues do NOT happen if we had attempted to merge `aaa::bbb` and `ccc::bbb` by renaming `aaa` to `ccc`

**Expected behavior**
Categorized tags should have been merged.

**Desktop (please complete the following information):**
 - Freeplane v1.12.6-pre04

**Logs**

~~~
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.freeplane.features.icon.mindmapmode.TagEditor.lambda$new$3(TagEditor.java:414)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.freeplane.features.icon.mindmapmode.TagEditor.<init>(TagEditor.java:415)
	at org.freeplane.features.icon.mindmapmode.MIconController.editTags(MIconController.java:703)
	at org.freeplane.features.icon.mindmapmode.EditTagsAction.actionPerformed(EditTagsAction.java:25)
	at org.freeplane.core.ui.AccelerateableAction.actionPerformed(AccelerateableAction.java:128)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at org.freeplane.core.ui.components.JFreeplaneMenuItem.processMouseEvent(JFreeplaneMenuItem.java:63)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
~~~

**Comment by dpolivaev** [comment]
Preview 1.12.6_05
