### ISSUE TITLE
Error when merging uncategorized tags

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2039]
**Describe the bug**
Error when merging uncategorized tags

**To Reproduce**
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `aaa`
   - `bbb`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Merge both tags into one by changing the name of `aaa` to `bbb`
1. =>>> ERROR: the following exception is logged

~~~
SEVERE: Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: path in TreePath must be non null.
	at java.desktop/javax.swing.tree.TreePath.<init>(TreePath.java:124)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.merge(TagCategoryEditor.java:462)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.merge(TagCategoryEditor.java:349)
	at org.freeplane.features.icon.mindmapmode.TagCategoryEditor$TagRenamer.lambda$treeNodesInserted$1(TagCategoryEditor.java:409)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
~~~

**Expected behavior**
Merging tags should not produce errors

**Desktop (please complete the following information):**
- freeplane-1.12.6-pre06

**Comment by dpolivaev** [comment]
Preview 1.12.6_07
