### ISSUE TITLE
File not found: Manifest.mf

### ISSUE THREAD

**Issue by Overloader6** [freeplane/freeplane#2064]
**Describe the bug**
I'm on nixos and tried to install and run freeplane and got the following error:
```
 ❯ nix run nixpkgs#freeplane
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
WARNING: package sun.swing.shell not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.launcher.Launcher (file:/nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/freeplanelauncher.jar)
WARNING: Please consider reporting this to the maintainers of org.freeplane.launcher.Launcher
WARNING: System::setSecurityManager will be removed in a future release
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2020 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.11.
java.io.FileNotFoundException: /nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.knopflerfish.framework.bundlestorage.file.Archive.downloadArchive(Archive.java:226)
	at org.knopflerfish.framework.bundlestorage.file.BundleArchiveImpl.<init>(BundleArchiveImpl.java:134)
	at org.knopflerfish.framework.bundlestorage.file.BundleStorageImpl.insertBundleJar(BundleStorageImpl.java:219)
	at org.knopflerfish.framework.Bundles.install0(Bundles.java:161)
	at org.knopflerfish.framework.SecurePermissionOps$14.run(SecurePermissionOps.java:737)
	at org.knopflerfish.framework.SecurePermissionOps$14.run(SecurePermissionOps.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.knopflerfish.framework.SecurePermissionOps.callInstall0(SecurePermissionOps.java:732)
	at org.knopflerfish.framework.Bundles.install(Bundles.java:118)
	at org.knopflerfish.framework.BundleContextImpl.installBundle(BundleContextImpl.java:125)
	at org.knopflerfish.framework.Main.handleArgs(Main.java:549)
	at org.knopflerfish.framework.Main.start(Main.java:224)
	at org.freeplane.launcher.Launcher.startFramework(Launcher.java:335)
	at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:303)
	at org.freeplane.launcher.Launcher.main(Launcher.java:88)
Error: Command "-istart org.freeplane.core" failed, Failed to install bundle: java.io.FileNotFoundException: /nix/store/q8rj5bznm7nxpkcid9rsr2ga4qkrjjd3-freeplane-1.11.14/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF (No such file or directory)
```
If you're not familiar with nixos: the `nix run nixpkgs#freeplane` is just shorthand for downloading freeplane, running it and deleting it once it's done

**To Reproduce**
1. Download and install freeplane on nixos
2. Run it

**Expected behavior**
Freeplane should just like... run?

**Desktop (please complete the following information):**
 - OS: NixOS 24.11.20240926.1925c60 (Vicuna) x86_64 
 - Version 1.11.14
 - Java Version: 17

**Comment by dpolivaev** [comment]
Please report the problem to people who create the distribution for your package manager, it is not done here.

**Comment by raboof** [comment]
> Please report the problem to people who create the distribution for your package manager, it is not done here

That's fair! We build this package by doing a gradle build and then copying the contents of the resulting BIN directory into the package. We've found that the META-INF directory does not reliably get created when we enable the `--parallel` flag to gradle. For now we'll work around the issue by not adding `--parallel` - though it might be worth looking into why the META-INF (both for `share/freeplane/core/org.freeplane.core` and for various `share/freeplane/plugins/org.freeplane.plugin.*`) are sometimes missing when parallelism is enabled.
