### ISSUE TITLE
Clicking a hyperlink on a node raising URI SyntaxException

### ISSUE THREAD

**Issue by tignioj** [freeplane/freeplane#224]
# INFO
- OS info: Wndows10 Pro  21H1 / Mac OS15.7 Catalina
- java version: 11.0.
- freeplane_version = 1.9.7
- freeplane_xml_version = freeplane 1.9.0
- java_version = 11; 

# Purpose
Click the hyperlink in the node content/Core/annotations and open OneNote

# Scence
- Scence1: Click a hyper link in node core/detail/note, unable to open the link properly.
- Scence2: Execute a groovy script, set the `node.link.text = [my link]` or `node.link.setUri(new java.net.URI(my link)` raise SyntaxException.
![Snipaste_2021-08-24_09-56-04](https://user-images.githubusercontent.com/38057269/130543436-5575d148-9572-4e2d-8020-8c5617f50bab.png)

- my link info
```
onenote:https://d.docs.live.net/99e990bdba42b2ad/文档/MyNoteBook/New%20Section%201.one#Page1Test&section-id={EEFEF6E4-101C-4F03-BE81-21B82A655B81}&page-id={BE156244-C3B1-4208-BDF7-B11F2A6638A9}&object-id={5E7DAE24-AB39-49B1-833A-C59C8A8D189F}&1F
```

# URISyntaxException 
```
java.net.URISyntaxException: Illegal character in fragment at index 106: onenote:https://d.docs.live.net/99e990bdba42b2ad/文档/MyNoteBook/New%20Section%201.one#Page1Test&section-id={EEFEF6E4-101C-4F03-BE81-21B82A655B81}&page-id={BE156244-C3B1-4208-BDF7-B11F2A6638A9}&object-id={5E7DAE24-AB39-49B1-833A-C59C8A8D189F}&1F
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parse(URI.java:3130)
	at java.base/java.net.URI.<init>(URI.java:600)
	at org.freeplane.core.util.Hyperlink.<init>(Hyperlink.java:16)
	at org.freeplane.view.swing.ui.DefaultNodeMouseMotionListener.loadLink(DefaultNodeMouseMotionListener.java:134)
	at org.freeplane.view.swing.ui.DefaultNodeMouseMotionListener.access$000(DefaultNodeMouseMotionListener.java:32)
	at org.freeplane.view.swing.ui.DefaultNodeMouseMotionListener$1.run(DefaultNodeMouseMotionListener.java:94)
	at org.freeplane.core.ui.DoubleClickTimer$1.actionPerformed(DoubleClickTimer.java:39)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
**where index of 106 is a character "{"**

note: This link copy from onenote `Copy link to paragraph`, I can paste into the browser and open the link correctly, But **I can't change the syntax of this kind of link.**

![image](https://user-images.githubusercontent.com/38057269/130542272-301bdcac-9cf6-4737-baf0-1a4fb0dfc7cb.png)

# Tracing Error: URI Syntax Exception
These exceptions are raised from `package org.freeplane.core.util.HyperLink` line 14
```
	public Hyperlink(String uriString) throws URISyntaxException {
		super();
		this.uriString = uriString;
		this.uri = new URI(uriString);  # <--- raising exception
	}
```

Then I check the java.net.URI source code, 

> Constructs a URI by parsing the given string.
This constructor parses the given string exactly as specified by the grammar in RFC 2396 , Appendix A,

so I check teh [Appendix A](https://www.ietf.org/rfc/rfc2396.txt). and search for chararcter '{'
```
 RFC 2396                   URI Generic Syntax                August 1998


   Other characters are excluded because gateways and other transport
   agents are known to sometimes modify such characters, or they are
   used as delimiters.

   unwise      = "{" | "}" | "|" | "\" | "^" | "[" | "]" | "`"

   Data corresponding to excluded characters must be escaped in order to
   be properly represented within a URI.
```

# What I'v try
## 1. Add a hyperlink manually
![image](https://user-images.githubusercontent.com/38057269/130543950-82c07039-110c-45de-aeed-72c2f6507e25.png)
![image](https://user-images.githubusercontent.com/38057269/130544025-b9696763-8988-497c-8e19-6c774b6cec83.png)
It works, but if you have a lot of links, it's cumbersome to do this

## 2. **programmatically** change links by script.
Manually replace these I special characters.
```
// Extract hyperlink
String uriString = ""
Pattern p = Pattern.compile("href=\"(onenote:http.*?)\">");
Matcher m = p.matcher(node.text);
if (m.find()) { uriString = m.group(1); } else { return; }

// Escape manually
uriStrEscape = uriString.replace("{", "%7B").replace("}", "%7D")

node.text = node.text.replaceAll("href=\"(onenote:.*?)\">", "href=\"" + uriStrEscape + "\">")
node.link.setUri(new URI(uriStrEscape))
```
Now I can open OneNote by clicking on the link, But I don't know if that's going to replace some characters by mistake

# Expect
These extra steps are all because the URI cannot be resolved successfully, so I have these problem:
- How to properly resolve these URI containing special symbols without having to manually modify them.
- If the first problem cannot be solved, then I need to write a script to programmatically modify the links, so I wonder if there is a universal URI parser to transfer this particular symbol?

**Comment by dpolivaev** [comment]
https://github.com/freeplane/freeplane/commit/5cf82dd02c304114a24d215b179e902300de6206
