### ISSUE TITLE
Freeplane hangs at start when running with -N (batch mode, nonInteractive)

### ISSUE THREAD

**Issue by bekoeppel** [freeplane/freeplane#227]
I'm following the Wiki (https://www.freeplane.org/wiki/index.php/Batch_Jobs) to run Freeplane in batch mode. I would like to run one of my scripts and then exit Freeplane again, without ever showing the User Interface.

* When I start Freeplane with `-XHelloWorld_on_single_node`, the UI opens, and the script successfully runs. 
* When I start Freeplane with `-XHelloWorld_on_single_node -S`, the UI opens, the script successfully runs, then Freeplane closes
* But when I add `-N` to suppress the UI from opening, running with `-XHelloWorld_on_single_node -S -N`, Freeplane gets stuck before doing anything.

I initially thought there could be something wrong with my script, but even when I try to run a built-in menu item like `-XMoveToRootAction`, it hangs.

Full command:
```
freeplane.sh -U /home/beni/tempfpdir -XMoveToRootAction -S -N test.mm
```

Script: (in `tempfpdir/1.9.x/scripts/HelloWorld.groovy`)
```
// @ExecutionModes({ON_SINGLE_NODE})
println "Hello, World!"
```

Freeplane Version:
```
Freeplane 1.9.7
a3e94d79a8bea132914cc65753ef1f242ee0c821 Dimitry Polivaev 2021-07-30T19:57:40Z
Java version: 11.0.11
```

The application hangs after these log lines:
```
INFO: language resources for en found
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.9.7; freeplane_xml_version = freeplane 1.9.0
git revision = a3e94d79a8bea132914cc65753ef1f242ee0c821 Dimitry Polivaev 2021-07-30T19:57:40Z
java_version = 11.0.11; os_name = Linux; os_version = 5.11.0-27-generic
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils warn
WARNING: Exception in org.freeplane.core.ui.components.OneTouchCollapseResizer.setExpanded(enabled): java.lang.RuntimeException: Method not implemented
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [/home/beni/tempfpdir/1.9.x/compiledscripts, /home/beni/tempfpdir/1.9.x/lib]
Sep 04, 2021 9:51:58 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/script/defaults.properties
Sep 04, 2021 9:51:59 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/formula/defaults.properties
Framework launched
```

Stack Trace:
```
2021-09-04 21:52:59
Full thread dump OpenJDK 64-Bit Server VM (11.0.11+9-Ubuntu-0ubuntu2.20.04 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007f2518001ef0, length=12, elements={
0x00007f2558294800, 0x00007f2558296800, 0x00007f255829c000, 0x00007f255829e000,
0x00007f25582a0000, 0x00007f25582a2000, 0x00007f25582a4000, 0x00007f25582ea800,
0x00007f2558423000, 0x00007f24ec7eb800, 0x00007f2558017000, 0x00007f2518001000
}

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=1.05ms elapsed=12.83s tid=0x00007f2558294800 nid=0x8ac1b waiting on condition  [0x00007f252b579000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.11/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.11/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.11/Reference.java:213)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=1.78ms elapsed=12.83s tid=0x00007f2558296800 nid=0x8ac1c in Object.wait()  [0x00007f252b478000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <0x00000000c0324d10> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000c0324d10> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.11/Finalizer.java:170)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.36ms elapsed=12.83s tid=0x00007f255829c000 nid=0x8ac1d runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.06ms elapsed=12.83s tid=0x00007f255829e000 nid=0x8ac1e runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=1297.36ms elapsed=12.83s tid=0x00007f25582a0000 nid=0x8ac1f waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #9 daemon prio=9 os_prio=0 cpu=813.44ms elapsed=12.83s tid=0x00007f25582a2000 nid=0x8ac20 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #10 daemon prio=9 os_prio=0 cpu=0.15ms elapsed=12.82s tid=0x00007f25582a4000 nid=0x8ac21 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #11 daemon prio=8 os_prio=0 cpu=0.79ms elapsed=12.81s tid=0x00007f25582ea800 nid=0x8ac22 in Object.wait()  [0x00007f252a8ae000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <0x00000000c03250d0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000c03250d0> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.11/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.11/InnocuousThread.java:134)

   Locked ownable synchronizers:
	- None

"startlevel job" #12 prio=5 os_prio=0 cpu=32.85ms elapsed=12.63s tid=0x00007f2558423000 nid=0x8ac25 in Object.wait()  [0x00007f252a5aa000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on <0x00000000c05f9b18> (a org.knopflerfish.framework.Queue)
	at java.lang.Object.wait(java.base@11.0.11/Object.java:328)
	at org.knopflerfish.framework.Queue.removeWait(Queue.java:114)
	- waiting to re-lock in wait() <0x00000000c05f9b18> (a org.knopflerfish.framework.Queue)
	at org.knopflerfish.framework.Queue.remove(Queue.java:137)
	at org.knopflerfish.framework.StartLevelController.run(StartLevelController.java:169)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

   Locked ownable synchronizers:
	- None

"pool-1-thread-1" #18 prio=5 os_prio=0 cpu=1.99ms elapsed=11.16s tid=0x00007f24ec7eb800 nid=0x8ac82 waiting on condition  [0x00007f252a3a8000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  <0x00000000c014c200> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.11/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.11/LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.11/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

   Locked ownable synchronizers:
	- None

"DestroyJavaVM" #19 prio=5 os_prio=0 cpu=205.67ms elapsed=11.16s tid=0x00007f2558017000 nid=0x8ac14 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Attach Listener" #20 daemon prio=9 os_prio=0 cpu=0.44ms elapsed=0.12s tid=0x00007f2518001000 nid=0x8acd2 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=0 cpu=37.23ms elapsed=12.83s tid=0x00007f2558291800 nid=0x8ac1a runnable  

"GC Thread#0" os_prio=0 cpu=27.83ms elapsed=12.84s tid=0x00007f255802f000 nid=0x8ac15 runnable  

"GC Thread#1" os_prio=0 cpu=27.06ms elapsed=12.36s tid=0x00007f251c061000 nid=0x8ac2c runnable  

"GC Thread#2" os_prio=0 cpu=16.93ms elapsed=12.36s tid=0x00007f251c062800 nid=0x8ac2d runnable  

"GC Thread#3" os_prio=0 cpu=21.42ms elapsed=12.36s tid=0x00007f251c064000 nid=0x8ac2e runnable  

"GC Thread#4" os_prio=0 cpu=27.80ms elapsed=12.36s tid=0x00007f251c065800 nid=0x8ac2f runnable  

"GC Thread#5" os_prio=0 cpu=28.57ms elapsed=12.36s tid=0x00007f251c067000 nid=0x8ac30 runnable  

"GC Thread#6" os_prio=0 cpu=24.07ms elapsed=12.36s tid=0x00007f251c068800 nid=0x8ac31 runnable  

"GC Thread#7" os_prio=0 cpu=20.91ms elapsed=12.36s tid=0x00007f251c06a000 nid=0x8ac32 runnable  

"G1 Main Marker" os_prio=0 cpu=0.45ms elapsed=12.84s tid=0x00007f255804b000 nid=0x8ac16 runnable  

"G1 Conc#0" os_prio=0 cpu=9.15ms elapsed=12.84s tid=0x00007f255804d000 nid=0x8ac17 runnable  

"G1 Conc#1" os_prio=0 cpu=9.76ms elapsed=11.18s tid=0x00007f2534001000 nid=0x8ac81 runnable  

"G1 Refine#0" os_prio=0 cpu=4.87ms elapsed=12.83s tid=0x00007f25581fb000 nid=0x8ac18 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=2.44ms elapsed=12.83s tid=0x00007f25581fd000 nid=0x8ac19 runnable  
"VM Periodic Task Thread" os_prio=0 cpu=10.23ms elapsed=12.80s tid=0x00007f25582ee000 nid=0x8ac23 waiting on condition  

JNI global refs: 9, weak refs: 0
```

**Comment by dpolivaev** [comment]
I checked it, headless mode implementation currently does process user options -X and -N.

**Comment by dpolivaev** [comment]
I don't really know how important it is and if I should rather fix documentation by removing non-supported options.

**Comment by bekoeppel** [comment]
Hi Dimitry!

Thanks for your response. If I understand you correctly, a command like this works fine for you?

```
./freeplane.sh -U "$PWD"/tempfpdir -XHelloWorld_on_single_node -N test.mm
```

I just tested the same on the latest version 1.9.0-alpha-pre05 as well. In my case, this again just leads to the message `Framework launched` and then nothing happens (like in my initial message). 

If it works for you, but not for me - what OS and Window Manager are you using? Then I'll try the same and see if I can narrow the problem down. Thank you!

**Comment by dpolivaev** [comment]
I am sorry for the confusion, I wanted to write that the headless mode currently does NOT process user options -X and -S.
Actually, in the headless mode, no menu is built, and therefore supporting scripts in headless mode would require another approach.

The headless mode was originally introduced to be used with another launcher which was starting Freeplane launcher internally using org.freeplane.launcher.Launcher.launchHeadless() method and using Freeplane API for map processing.

**Comment by dpolivaev** [comment]
I reworked this part in the latest preview version 1.10.1_06.
Now you can combine command-line options `-N` and `-S` with a new option `-R` followed by the file path of any script you want to execute at the start. Such scripts run without any security restrictions. They do not have any node variable assigned. Selection is supported only if you start Freeplane with the UI.

**Comment by dpolivaev** [comment]
You can start Freeplane with any number of scripts by repeating the `-R` option as many times as needed.

**Comment by bekoeppel** [comment]
Awesome, thank you so much! I just gave it a try, and managed to get it to work :+1:.

One question - not sure if I understood this correctly:

> They do not have any node variable assigned.

That means the global variable `node` is null, so I can't get the map with `node.getMap()`. Is there another way to get a reference to the map, so I can start iterating over nodes of that map? Or is the idea that I'll open a file myself in my script, by doing something like this:

```
map = c.mapLoader("/home/beni/Test.mm").load()
root = map.getRoot()
```

**Comment by dpolivaev** [comment]
You have access to the controller `c` and can use all its methods not related to the selection. Your example should work.
