### ISSUE TITLE
map loader exception with multiple thread

### ISSUE THREAD

**Issue by petersun94** [freeplane/freeplane#323]
I was trying to load many mindmaps at a same time by using multiple threads. but I got a problem. 
is it illegle to to this in freeplane? 

*  script:

```java
def file1 = new File(node.mindMap.file.parent, "test1.mm")
def file2 = new File(node.mindMap.file.parent, "test2.mm")
def file3 = new File(node.mindMap.file.parent, "test3.mm")
def file4 = new File(node.mindMap.file.parent, "test4.mm")
def file5 = new File(node.mindMap.file.parent, "test5.mm")

def t1 = new Thread(() -> {
    def map1 = c.mapLoader(file1).mindMap
    ui.informationMessage(map1.root.plainText)
})
def t2 = new Thread(() -> {
    def map2 = c.mapLoader(file2).mindMap
    ui.informationMessage(map2.root.plainText)
})
def t3 = new Thread(() -> {
    def map3 = c.mapLoader(file3).mindMap
    ui.informationMessage(map3.root.plainText)
})
def t4 = new Thread(() -> {
    def map4 = c.mapLoader(file4).mindMap
    ui.informationMessage(map4.root.plainText)
})
def t5 = new Thread(() -> {
    def map5 = c.mapLoader(file5).mindMap
    ui.informationMessage(map5.root.plainText)
})

t1.start()
t2.start()
t3.start()
t4.start()
t5.start()

```

* files for test:
[MultiplaeThreadException.zip](https://github.com/freeplane/freeplane/files/8513391/MultiplaeThreadException.zip)

* Screenshots
![image](https://user-images.githubusercontent.com/97656893/164015917-42bc11e5-6392-47b0-8ea7-08f75dd989de.png)
![image](https://user-images.githubusercontent.com/97656893/164016421-e4178379-a227-49ce-8b62-04c607ef0590.png)
![image](https://user-images.githubusercontent.com/97656893/164016446-a9d8bbb9-cc73-47f6-ba97-98ec11813f0d.png)
> the message should be `test...`

**Comment by petersun94** [comment]
* exception: 

```
at 2022-04-19 13:34:19 CMT,  hash 66de20035c972e58d1bbf58f98d6a8b9
previous report : at 2022-04-19 13:21:48 CMT,  hash b5d9a36c262da897a86e390b6681f421
freeplane_version = 1.10.1 alpha; freeplane_xml_version = freeplane 1.9.13
git revision = 1fe6c92037c77c86b6cb46e6ead37e2ede2abbcc Dimitry Polivaev 2022-04-02T14:37:45Z
java_version = 11.0.11; os_name = Windows 10; os_version = 10.0
Apr 19, 2022 9:34:18 PM org.freeplane.core.util.LogUtils severe
SEVERE: Can not process attributeVSHIFT_QUANTITY = '-31.5 pt'
java.lang.NumberFormatException: For input string: ".1371513715E2E2"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.text.DigitList.getDouble(DigitList.java:169)
	at java.base/java.text.DecimalFormat.parse(DecimalFormat.java:2126)
	at java.base/java.text.NumberFormat.parse(NumberFormat.java:429)
	at org.freeplane.api.Quantity.fromString(Quantity.java:28)
	at org.freeplane.features.nodelocation.LocationBuilder$1.setAttribute(LocationBuilder.java:42)
	at org.freeplane.core.io.xml.TreeXmlReader.addAttribute(TreeXmlReader.java:110)
	at org.freeplane.core.io.xml.TreeXmlReader.addAttribute(TreeXmlReader.java:129)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:291)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
	at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
	at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
	at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
	at org.freeplane.n3.nanoxml.StdXMLParser.scanData(StdXMLParser.java:441)
	at org.freeplane.n3.nanoxml.StdXMLParser.parse(StdXMLParser.java:118)
	at org.freeplane.core.io.xml.TreeXmlReader.load(TreeXmlReader.java:257)
	at org.freeplane.core.io.xml.TreeXmlReader.load(TreeXmlReader.java:334)
	at org.freeplane.features.map.MapReader$NodeTreeCreator.create(MapReader.java:62)
	at org.freeplane.features.map.MapReader$NodeTreeCreator.createNodeTreeFromXml(MapReader.java:76)
	at org.freeplane.features.map.MapReader.createNodeTreeFromXml(MapReader.java:170)
	at org.freeplane.features.map.MapReader.createNodeTreeFromXml(MapReader.java:163)
	at org.freeplane.features.url.mindmapmode.MFileManager.loadTreeImpl(MFileManager.java:562)
	at org.freeplane.features.url.mindmapmode.MFileManager.loadTree(MFileManager.java:532)
	at org.freeplane.features.url.mindmapmode.MapLoader.loadMap(MapLoader.java:294)
	at org.freeplane.features.url.mindmapmode.MapLoader.access$200(MapLoader.java:35)
	at org.freeplane.features.url.mindmapmode.MapLoader$1.run(MapLoader.java:230)
	at org.freeplane.features.url.mindmapmode.MapLoader$1.run(MapLoader.java:221)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.freeplane.features.url.mindmapmode.MapLoader.loadMap(MapLoader.java:221)
	at org.fre
eplane.features.url.mindmapmode.MapLoader.getMap(MapLoader.java:134)
	at org.freeplane.plugin.script.proxy.LoaderProxy.getMindMap(LoaderProxy.java:127)
	at org.freeplane.plugin.script.proxy.LoaderProxy.getMindMap(LoaderProxy.java:16)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at Script1$_run_closure1.doCall(Script1.groovy:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.run(Closure.java:500)
	at java.base/java.lang.Thread.run(Thread.java:834)
...
```

**Comment by dpolivaev** [comment]
Unfortunately, multithreading is generally not supported.
I checked your example and found at least 3 places which go wrong if maps are loaded in different threads simulteneously.
Just to give you an example, it is a non thread safe `static DecimalFormat  ROUNDING_FORMAT ` used in `org.freeplane.api.Quantity<U>`
