### ISSUE TITLE
1.10.x - AccessControlException: access denied when more than one groovy script in lib

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#329]
**Describe the bug**
When there is more than one groovy script in `<user-dir>/lib/`, Freeplane 1.10.1 fails to compile them.

**To Reproduce**

1. Unpack [freeplane-lib.zip](https://github.com/freeplane/freeplane/files/8557884/freeplane-lib.zip) to `<user-dir>/lib/`
2. Start Freeplane
3. See console output or log.0

```log
java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/m/.freeplane/1.10.x/lib/A.groovy" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.codehaus.groovy.control.io.FileReaderSource.getReader(FileReaderSource.java:63)
	at org.apache.groovy.parser.antlr4.AstBuilder.createCharStream(AstBuilder.java:398)
	at org.apache.groovy.parser.antlr4.AstBuilder.<init>(AstBuilder.java:383)
	at org.apache.groovy.parser.antlr4.Antlr4ParserPlugin.buildAST(Antlr4ParserPlugin.java:56)
	at org.codehaus.groovy.control.SourceUnit.buildAST(SourceUnit.java:250)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Workaround**
Put the scripts one by one in `<user-dir>/lib/`, restarting Freeplane each time

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux
 - Java Version: 17.0.2, 17.0.3

**Comment by dpolivaev** [comment]
Preview 1.10.2

**Comment by macmarrum** [comment]
Tested 🆗 
Looks good 👍 
Thanks
