### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Graninius** [freeplane/freeplane#350]
It doesn't start at all
```bash
❯ freeplane
*org.knopflerfish.framework.readonly=true
*org.knopflerfish.gosg.jars=reference:file:/usr/share/freeplane/core/
*org.freeplane.user.dir=/home/feltsi
*org.freeplane.basedirectory=/usr/share/freeplane
org.freeplane.globalresourcedir=/usr/share/freeplane/resources
*java.security.policy=/usr/share/freeplane/freeplane.policy
*org.osgi.framework.storage=/usr/share/freeplane/fwdir
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:291)
        at org.freeplane.launcher.Launcher.main(Launcher.java:88)
```
Manjaro KDE, unstabile
FreePlane 1.9.14-1 from of.repo
Java 18 by default (the trick with UNSUPPORTED JAVA VERSION=1 doesn't work)

**Comment by dpolivaev** [comment]
Java 16 and above needs Freeplane 1.10.x
