### ISSUE TITLE
Error message occurs when pressing <F1> (Documentation)

### ISSUE THREAD

**Issue by weveh** [freeplane/freeplane#463]
**Describe the bug**
When prssing <F1> or accessing Documentation by > Help> Documentation an error ocurs in the status bar 

**To Reproduce**
Press <F1>

**Expected behavior**
User Guide opens

**Mind map files**

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/107927499/174789964-26fd2eb4-d609-4cad-b4d4-33fb2e58bb26.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Java Version 8 update 331 (build 1.8.0_331-b09)

**Additional context**
Log entry:

STDOUT: jun 21, 2022 1:23:16 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.9.14; freeplane_xml_version = freeplane 1.9.13
git revision = 64acbf326fe9b4e8eaa2cc8d2c183a02f5318387 Dimitry Polivaev 2022-03-19T15:27:19Z
java_version = 1.8.0_331; os_name = Windows 8.1; os_version = 6.3
STDOUT: jun 21, 2022 1:23:40 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: jun 21, 2022 1:23:40 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\weveh00\AppData\Roaming\Freeplane\1.9.x\compiledscripts, C:\Users\weveh00\AppData\Roaming\Freeplane\1.9.x\lib]
STDOUT: jun 21, 2022 1:23:40 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: jun 21, 2022 1:23:41 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: jun 21, 2022 1:23:41 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [js, groovy]
STDOUT: Framework launched
STDOUT: jun 21, 2022 1:23:48 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: jun 21, 2022 1:23:55 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: jun 21, 2022 1:24:05 PM org.freeplane.core.util.LogUtils severe
SEVERE: 
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections.min(Unknown Source)
	at org.freeplane.features.map.mindmapmode.MMapController.getPathToNearestTargetClone(MMapController.java:660)
	at org.freeplane.features.map.mindmapmode.MMapController.moveNodeAndItsClones(MMapController.java:627)
	at org.freeplane.features.map.mindmapmode.SummaryNodeMapUpdater.updateSummaryNodes(SummaryNodeMapUpdater.java:62)
	at org.freeplane.features.map.mindmapmode.SummaryNodeMapUpdater.updateSummaryNodes(SummaryNodeMapUpdater.java:71)
	at org.freeplane.features.map.mindmapmode.SummaryNodeMapUpdater.updateSummaryNodes(SummaryNodeMapUpdater.java:71)
	at org.freeplane.features.map.mindmapmode.SummaryNodeMapUpdater.updateSummaryNodes(SummaryNodeMapUpdater.java:71)
	at org.freeplane.features.map.mindmapmode.SummaryNodeMapUpdater.onCreate(SummaryNodeMapUpdater.java:26)
	at org.freeplane.features.map.MapController.fireMapCreated(MapController.java:628)
	at org.freeplane.features.url.mindmapmode.MapLoader.loadMap(MapLoader.java:256)
	at org.freeplane.features.url.mindmapmode.MapLoader.getMap(MapLoader.java:134)
	at org.freeplane.features.map.mindmapmode.MMapController.openDocumentationMap(MMapController.java:1002)
	at org.freeplane.features.map.mindmapmode.MMapController.newDocumentationMap(MMapController.java:978)
	at org.freeplane.features.help.DocumentationAction$1.run(DocumentationAction.java:44)
	at org.freeplane.core.ui.components.UITools$5.lambda$focusGained$0(UITools.java:773)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
STDOUT: jun 21, 2022 1:38:05 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/weveh00/AppData/Roaming/Freeplane/1.9.x/logs/]
STDOUT: jun 21, 2022 1:38:06 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/weveh00/AppData/Roaming/Freeplane/1.9.x/logs/]
STDOUT: jun 21, 2022 1:38:07 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/Users/weveh00/AppData/Roaming/Freeplane/1.9.x/logs/]

**Comment by dpolivaev** [comment]
Fixed in version 1.10.3 released as stable version
