### ISSUE TITLE
Node copy/paste is messed up on Chromebook

### ISSUE THREAD

**Issue by nborodikhin** [freeplane/freeplane#760]
Setup:
- chromebook
- stock Linux (https://chromeos.dev/en/linux)
 - runs in container
 - based on Debian bullseye
 - X11 via Sommelier Wayland compositor https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/vm_tools/sommelier/README.md
- freeplane (1.7, 1.10)

Use case:
- create new mind map
- create a node with text "node"
- copy node (Ctrl-C)
- paste node (Ctrl-C)

Expected:
- a copy of node inserted as a child

Actual:
- a strange text with a lot of hieroglyphic characters

Disabling a preference Behavior->Confirmations->Use rich text for pasted nodes helps.

**Comment by nborodikhin** [comment]
Example of how it looks:
![image](https://user-images.githubusercontent.com/1527671/196583716-bdf40cd1-0940-4148-b946-ec21733cc151.png)

It seems either the text in clipboard is wrong or encoding is not properly detected.  As a note, the paste into Google Doc running in the native Chrome works without any issue - with proper color, background color etc.

```
INFO: looking for scripts with the following endings: [groovy]
Oct 18, 2022 9:27:52 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Oct 18, 2022 9:27:56 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.Reader]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.Reader]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.Reader]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.CharBuffer]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.CharBuffer]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.CharBuffer]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[C]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[C]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[C]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=utf-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=utf-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.io.InputStream;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.nio.ByteBuffer;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=[B;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.Reader]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.lang.String]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.CharBuffer]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[C]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=unicode]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=utf-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-8]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16BE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=UTF-16LE]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=ISO-8859-1]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.io.InputStream;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=java.nio.ByteBuffer;charset=US-ASCII]
java.awt.datatransfer.DataFlavor[mimetype=text/plain;representationclass=[B;charset=US-ASCII]
java.lang.RuntimeException: !!! foo data flavor: java.awt.datatransfer.DataFlavor[mimetype=text/html;representationclass=java.lang.String], textFromClipboard: 㰀栀琀਀㰀栀攀愀搀㸀਀㰀猀琀礀氀攀 琀礀瀀攀㴀∀琀攀砀琀⼀挀猀猀∀㸀਀    戀漀搀礀 笀挀漀氀漀爀㨀 ⌀㌀挀㌀㠀㌀㘀㬀 昀漀渀琀ⴀ猀椀稀攀㨀 ㄀㄀瀀琀㬀 昀漀渀琀ⴀ昀愀洀椀氀礀㨀 ☀焀甀漀琀☀焀甀漀琀㬀Ⰰ 猀愀渀猀ⴀ猀攀爀椀昀㬀 紀਀氀椀 笀 氀椀猀琀ⴀ猀琀礀氀攀㨀 渀漀渀攀㬀  洀愀爀最椀渀㨀 　㬀 紀਀瀀 笀 洀愀爀最椀渀㨀 　㬀 紀਀਀猀瀀愀渀⸀氀 笀 挀漀氀漀爀㨀 爀攀搀㬀 昀漀渀琀ⴀ眀攀椀最栀琀㨀 戀漀氀搀㬀 紀਀਀愀⸀洀愀瀀渀漀搀攀㨀氀椀渀欀Ⰰ਀愀⸀洀愀瀀渀漀搀攀㨀瘀椀猀椀琀攀搀Ⰰ਀愀⸀洀愀瀀渀漀搀攀㨀愀挀琀椀瘀攀Ⰰ਀愀⸀洀愀瀀渀漀搀攀㨀栀漀瘀攀爀 笀਀    琀攀砀琀ⴀ搀攀挀漀爀愀琀椀漀渀㨀 渀漀渀攀㬀 挀漀氀漀爀㨀 戀氀愀挀欀㬀਀紀਀愀⸀洀愀瀀渀漀搀攀㨀栀漀瘀攀爀 笀 戀愀挀欀最爀漀甀渀搀㨀 ⌀攀攀攀攀攀　㬀 紀਀਀㰀⼀猀琀礀氀攀㸀਀㰀⼀栀攀愀搀㸀਀㰀戀漀搀礀 猀琀礀氀攀㴀∀戀愀挀欀最爀漀甀渀搀ⴀ挀漀氀漀爀㨀⌀昀戀昀㄀挀㜀㬀∀㸀਀㰀搀椀瘀 猀琀礀氀攀㴀∀戀愀挀欀最爀漀甀渀搀ⴀ挀漀氀漀爀㨀⌀昀戀昀㄀挀㜀㬀∀㸀਀㰀瀀㸀㰀猀瀀愀渀 猀琀礀氀攀㴀∀挀漀氀漀爀㨀 ⌀㈀㠀㈀㠀㈀㠀㬀 昀漀渀琀ⴀ猀椀稀攀㨀 ㄀㘀瀀琀㬀 昀漀渀琀ⴀ昀愀洀椀氀礀㨀 ☀焀甀漀琀㬀䐀椀愀氀漀最☀焀甀漀琀㬀Ⰰ 猀愀渀猀ⴀ猀攀爀椀昀㬀 ∀㸀渀漀搀攀㰀⼀猀瀀愀渀㸀਀    㰀瀀 猀琀礀氀攀㴀∀洀愀爀最椀渀ⴀ琀漀瀀㨀 　∀㸀਀      搀猀਀    㰀⼀瀀㸀਀  㰀⼀搀椀瘀㸀਀㰀⼀戀漀搀礀㸀਀㰀⼀栀琀洀氀㸀਀
        at org.freeplane.features.map.mindmapmode.clipboard.MMapClipboardController.getFlavorHandler(MMapClipboardController.java:587)
        at org.freeplane.features.map.mindmapmode.clipboard.MMapClipboardController.paste(MMapClipboardController.java:752)
        at org.freeplane.features.map.mindmapmode.clipboard.MMapClipboardController.paste(MMapClipboardController.java:739)
        at org.freeplane.features.map.mindmapmode.clipboard.MMapClipboardController.paste(MMapClipboardController.java:1025)
        at org.freeplane.features.clipboard.mindmapmode.MClipboardControllers.lambda$paste$2(MClipboardControllers.java:54)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.freeplane.features.clipboard.mindmapmode.MClipboardControllers.paste(MClipboardControllers.java:54)
        at org.freeplane.features.clipboard.mindmapmode.PasteAction.actionPerformed(PasteAction.java:38)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
        at org.freeplane.core.ui.ActionAcceleratorManager.processKeyBinding(ActionAcceleratorManager.java:454)
        at org.freeplane.main.mindmapmode.MModeControllerFactory$2.processKeyBinding(MModeControllerFactory.java:288)
        at org.freeplane.view.swing.ui.UserInputListenerFactory$2.processKeyBinding(UserInputListenerFactory.java:173)
        at org.freeplane.core.ui.components.FreeplaneMenuBar.processKeyBinding(FreeplaneMenuBar.java:101)
        at org.freeplane.main.application.MenuKeyProcessor.processKeyBinding(MenuKeyProcessor.java:26)
        at org.freeplane.main.application.ConnectedToMenuView.processKeyBinding(ConnectedToMenuView.java:41)
        at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3009)
        at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
        at java.desktop/java.awt.Component.processEvent(Component.java:6403)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
```

**Comment by nborodikhin** [comment]
The content of clipboard looks OK:
```
username~$ xclip -o -t TARGETS
UTF8_STRING
TEXT
STRING
text/plain;charset=UTF-16
text/plain;charset=UTF-8
text/plain;charset=UTF-16BE
text/plain;charset=UTF-16LE
text/plain;charset=ISO-8859-1
text/plain;charset=US-ASCII
text/plain
JAVA_DATAFLAVOR:text/freeplane-nodes; class=java.lang.String
text/html;charset=UTF-16
text/html;charset=UTF-8
text/html;charset=UTF-16BE
text/html;charset=UTF-16LE
text/html;charset=ISO-8859-1
text/html;charset=US-ASCII
text/html
JAVA_DATAFLAVOR:text/drop-action; class=java.lang.String

username@penguin:~$ xclip -o -t 'text/html'
<html>
<head>
<style type="text/css">
    body {color: #3c3836; font-size: 11pt; font-family: &quot;SansSerif&quot;, sans-serif; }
li { list-style: none;  margin: 0; }
p { margin: 0; }

span.l { color: red; font-weight: bold; }

a.mapnode:link,
a.mapnode:visited,
a.mapnode:active,
a.mapnode:hover {
    text-decoration: none; color: black;
}
a.mapnode:hover { background: #eeeee0; }

</style>
</head>
<body style="background-color:#fbf1c7;">
<div style="background-color:#fbf1c7;">
<p><span style="color: #282828; font-size: 16pt; font-family: &quot;Dialog&quot;, sans-serif; ">node</span>
    <p style="margin-top: 0">
      ds
    </p>
  </div>
</body>
</html>
```
