### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#780]
Thanks. Well, here is the log message. I don't really know what the problem is. The software works well, I didn't notice anything unusual.

```
STDOUT: Oct 27, 2022 1:54:53 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.10.4; freeplane_xml_version = freeplane 1.9.13
git revision = d5b3aebcb36188c64ce4d730eeb2f8ef61f0d68c Dimitry Polivaev 2022-09-10T15:25:55Z
java_version = 17.0.4.1; os_name = Linux; os_version = 5.19.16-2-MANJARO
STDOUT: Oct 27, 2022 1:54:56 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
STDOUT: Oct 27, 2022 1:54:56 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
STDOUT: Framework launched
STDOUT: Oct 27, 2022 1:54:56 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://2:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [/home/jabba/.config/freeplane/1.10.x/compiledscripts, /home/jabba/.config/freeplane/1.10.x/lib]
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://9:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://9:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 27, 2022 1:54:57 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Oct 27, 2022 1:55:00 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 15, Tab count: 15
STDERR: at java.desktop/javax.swing.JTabbedPane.checkIndex(JTabbedPane.java:1793)
STDERR: at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:621)
STDERR: at net.infonode.tabbedpanel.theme.internal.laftheme.PaneUI.initTabLocations(PaneUI.java:1122)
STDERR: at net.infonode.tabbedpanel.theme.internal.laftheme.PaneUI.paintContentArea(PaneUI.java:872)
STDERR: at net.infonode.tabbedpanel.theme.LookAndFeelTheme$3$3.paint(LookAndFeelTheme.java:228)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintComponent(ShapedPanel.java:205)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at net.infonode.tabbedpanel.TabbedPanel$ShadowPanel.paint(TabbedPanel.java:1604)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
STDERR: at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
STDERR: at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
STDERR: at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
STDERR: at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
STDERR: at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
STDERR: at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
STDERR: at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
STDERR: at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
STDERR: at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
STDERR: at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
STDERR: at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDOUT: Oct 27, 2022 4:00:29 PM org.freeplane.core.util.LogUtils info
INFO: execute [xdg-open, file:/home/jabba/.config/freeplane/1.10.x/logs/]
```

_Originally posted by @jabbalaci in https://github.com/freeplane/freeplane/discussions/779#discussioncomment-3982461_

**Comment by ilpssun** [comment]
Same thing here, I attached the full log.

```
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 4, Tab count: 4
STDERR: at java.desktop/javax.swing.JTabbedPane.checkIndex(JTabbedPane.java:1800)
```

[log.0.txt](https://github.com/freeplane/freeplane/files/14064795/log.0.txt)

I have 8 mindmaps open (if that is relevant).

**Comment by ilpssun** [comment]
The software continues to function properly, as far as I can tell.  I cannot reliably reproduce the bug, although it has occurred several times over the last few days.
