### ISSUE TITLE
Remove or replace deprecated Java Security Manager

### ISSUE THREAD

**Issue by EwoutH** [freeplane/freeplane#841]
**Describe the bug**
The Java Security Manager is deprecated and marked for removal in a future Java version. It's currently used in many places, see this [CI log](https://github.com/EwoutH/freeplane/actions/runs/3530873584/jobs/5923349542#step:4:1088).

See for more information: [JEP 411: Deprecate the Security Manager for Removal](https://openjdk.org/jeps/411)

**To Reproduce**
1. Run `gradle build`.

**Environment**
 - OS: Ubuntu 20.04 LTS
 - Java Version: 17 LTS and 18

**Additional context**
See [this CI run](https://github.com/EwoutH/freeplane/actions/runs/3530873584/jobs/5923349542).

**Comment by new-gen23** [comment]
Tested on Ubuntu 22.10. Returns:
`*org.knopflerfish.framework.readonly=true
*org.knopflerfish.gosg.jars=reference:file:/usr/share/freeplane/core/
*org.freeplane.user.dir=/home/user
*org.freeplane.basedirectory=/usr/share/freeplane
org.freeplane.globalresourcedir=/usr/share/freeplane/resources
*java.security.policy=/usr/share/freeplane/freeplane.policy
*org.osgi.framework.storage=/usr/share/freeplane/fwdir
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:425)
	at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:279)
	at org.freeplane.launcher.Launcher.main(Launcher.java:87)
`
I'd say it's broken.

**Comment by JoDuENSCM** [comment]
Java 21 is still on LTS until 2028 to 2030 depending on the JRE provider, but the following LTS version (25) is available since september 2025 and due to the removal of the Security Manager in version 24, Freeplane is no longer usable with any recent version of Java.

Considering Freeplane does nothing critical to the system, and according to Oracle notes, it should be safe to remove any references to the Security Manager to make it compatible with the new JRE, but I'm not sure there would not be collateral damage...

https://docs.oracle.com/en/java/javase/24/security/security-manager-is-permanently-disabled.html
https://openjdk.org/jeps/486
